/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuditDetails
 */
public class AuditDetailsTest {
    private final AuditDetails model = new AuditDetails();

    /**
     * Model tests for AuditDetails
     */
    @Test
    public void testAuditDetails() {
        // TODO: test AuditDetails
    }

    /**
     * Test the property 'audDateTime'
     */
    @Test
    public void audDateTimeTest() {
        // TODO: test audDateTime
    }

    /**
     * Test the property 'audKey1Label'
     */
    @Test
    public void audKey1LabelTest() {
        // TODO: test audKey1Label
    }

    /**
     * Test the property 'audKey2Label'
     */
    @Test
    public void audKey2LabelTest() {
        // TODO: test audKey2Label
    }

    /**
     * Test the property 'audKey3Label'
     */
    @Test
    public void audKey3LabelTest() {
        // TODO: test audKey3Label
    }

    /**
     * Test the property 'audKey1Value'
     */
    @Test
    public void audKey1ValueTest() {
        // TODO: test audKey1Value
    }

    /**
     * Test the property 'audKey2Value'
     */
    @Test
    public void audKey2ValueTest() {
        // TODO: test audKey2Value
    }

    /**
     * Test the property 'audKey3Value'
     */
    @Test
    public void audKey3ValueTest() {
        // TODO: test audKey3Value
    }

    /**
     * Test the property 'audTableName'
     */
    @Test
    public void audTableNameTest() {
        // TODO: test audTableName
    }

    /**
     * Test the property 'audFieldName'
     */
    @Test
    public void audFieldNameTest() {
        // TODO: test audFieldName
    }

    /**
     * Test the property 'audOldValue'
     */
    @Test
    public void audOldValueTest() {
        // TODO: test audOldValue
    }

    /**
     * Test the property 'audNewValue'
     */
    @Test
    public void audNewValueTest() {
        // TODO: test audNewValue
    }

    /**
     * Test the property 'audAction'
     */
    @Test
    public void audActionTest() {
        // TODO: test audAction
    }

    /**
     * Test the property 'audSystemID'
     */
    @Test
    public void audSystemIDTest() {
        // TODO: test audSystemID
    }

}
