/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContactInfo;
import com.konfigthis.client.model.CreatorBackgroundCheckIntegration;
import com.konfigthis.client.model.CreatorPreferredLocale;
import com.konfigthis.client.model.Hyperlinks;
import com.konfigthis.client.model.Links;
import com.konfigthis.client.model.Name;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Creator
 */
public class CreatorTest {
    private final Creator model = new Creator();

    /**
     * Model tests for Creator
     */
    @Test
    public void testCreator() {
        // TODO: test Creator
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'personId'
     */
    @Test
    public void personIdTest() {
        // TODO: test personId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'integrationUserId'
     */
    @Test
    public void integrationUserIdTest() {
        // TODO: test integrationUserId
    }

    /**
     * Test the property 'isInternal'
     */
    @Test
    public void isInternalTest() {
        // TODO: test isInternal
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'preferredLocale'
     */
    @Test
    public void preferredLocaleTest() {
        // TODO: test preferredLocale
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'contactInfo'
     */
    @Test
    public void contactInfoTest() {
        // TODO: test contactInfo
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'hyperlinks'
     */
    @Test
    public void hyperlinksTest() {
        // TODO: test hyperlinks
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'backgroundCheckIntegration'
     */
    @Test
    public void backgroundCheckIntegrationTest() {
        // TODO: test backgroundCheckIntegration
    }

}
