/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeSupervisorDetails
 */
public class EmployeeSupervisorDetailsTest {
    private final EmployeeSupervisorDetails model = new EmployeeSupervisorDetails();

    /**
     * Model tests for EmployeeSupervisorDetails
     */
    @Test
    public void testEmployeeSupervisorDetails() {
        // TODO: test EmployeeSupervisorDetails
    }

    /**
     * Test the property 'employeeID'
     */
    @Test
    public void employeeIDTest() {
        // TODO: test employeeID
    }

    /**
     * Test the property 'companyID'
     */
    @Test
    public void companyIDTest() {
        // TODO: test companyID
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'supervisorEmployeeID'
     */
    @Test
    public void supervisorEmployeeIDTest() {
        // TODO: test supervisorEmployeeID
    }

    /**
     * Test the property 'supervisorFirstName'
     */
    @Test
    public void supervisorFirstNameTest() {
        // TODO: test supervisorFirstName
    }

    /**
     * Test the property 'supervisorLastName'
     */
    @Test
    public void supervisorLastNameTest() {
        // TODO: test supervisorLastName
    }

    /**
     * Test the property 'supervisorEmployeeNumber'
     */
    @Test
    public void supervisorEmployeeNumberTest() {
        // TODO: test supervisorEmployeeNumber
    }

    /**
     * Test the property 'supervisorCompanyID'
     */
    @Test
    public void supervisorCompanyIDTest() {
        // TODO: test supervisorCompanyID
    }

    /**
     * Test the property 'supervisorCompanyCode'
     */
    @Test
    public void supervisorCompanyCodeTest() {
        // TODO: test supervisorCompanyCode
    }

    /**
     * Test the property 'supervisorStatusCode'
     */
    @Test
    public void supervisorStatusCodeTest() {
        // TODO: test supervisorStatusCode
    }

    /**
     * Test the property 'supervisorJobCode'
     */
    @Test
    public void supervisorJobCodeTest() {
        // TODO: test supervisorJobCode
    }

    /**
     * Test the property 'supervisorPositionCode'
     */
    @Test
    public void supervisorPositionCodeTest() {
        // TODO: test supervisorPositionCode
    }

    /**
     * Test the property 'supervisorEmail'
     */
    @Test
    public void supervisorEmailTest() {
        // TODO: test supervisorEmail
    }

    /**
     * Test the property 'supervisorWorkPhone'
     */
    @Test
    public void supervisorWorkPhoneTest() {
        // TODO: test supervisorWorkPhone
    }

    /**
     * Test the property 'supervisorPersonId'
     */
    @Test
    public void supervisorPersonIdTest() {
        // TODO: test supervisorPersonId
    }

}
