/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeePayDeductionElementsModel
 */
public class EmployeePayDeductionElementsModelTest {
    private final EmployeePayDeductionElementsModel model = new EmployeePayDeductionElementsModel();

    /**
     * Model tests for EmployeePayDeductionElementsModel
     */
    @Test
    public void testEmployeePayDeductionElementsModel() {
        // TODO: test EmployeePayDeductionElementsModel
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'systemId'
     */
    @Test
    public void systemIdTest() {
        // TODO: test systemId
    }

    /**
     * Test the property 'payDeductionId'
     */
    @Test
    public void payDeductionIdTest() {
        // TODO: test payDeductionId
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'payGroup'
     */
    @Test
    public void payGroupTest() {
        // TODO: test payGroup
    }

    /**
     * Test the property 'payDeductionName'
     */
    @Test
    public void payDeductionNameTest() {
        // TODO: test payDeductionName
    }

    /**
     * Test the property 'payDeductionDescription'
     */
    @Test
    public void payDeductionDescriptionTest() {
        // TODO: test payDeductionDescription
    }

    /**
     * Test the property 'periodStartId'
     */
    @Test
    public void periodStartIdTest() {
        // TODO: test periodStartId
    }

    /**
     * Test the property 'periodEndId'
     */
    @Test
    public void periodEndIdTest() {
        // TODO: test periodEndId
    }

    /**
     * Test the property 'periodStartName'
     */
    @Test
    public void periodStartNameTest() {
        // TODO: test periodStartName
    }

    /**
     * Test the property 'periodEndName'
     */
    @Test
    public void periodEndNameTest() {
        // TODO: test periodEndName
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'task'
     */
    @Test
    public void taskTest() {
        // TODO: test task
    }

    /**
     * Test the property 'recurring'
     */
    @Test
    public void recurringTest() {
        // TODO: test recurring
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'paymentOrDeductionIndicator'
     */
    @Test
    public void paymentOrDeductionIndicatorTest() {
        // TODO: test paymentOrDeductionIndicator
    }

}
