/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeStatus
 */
public class EmployeeStatusTest {
    private final EmployeeStatus model = new EmployeeStatus();

    /**
     * Model tests for EmployeeStatus
     */
    @Test
    public void testEmployeeStatus() {
        // TODO: test EmployeeStatus
    }

    /**
     * Test the property 'asOfDate'
     */
    @Test
    public void asOfDateTest() {
        // TODO: test asOfDate
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'triggerTermination'
     */
    @Test
    public void triggerTerminationTest() {
        // TODO: test triggerTermination
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusStartDate'
     */
    @Test
    public void statusStartDateTest() {
        // TODO: test statusStartDate
    }

    /**
     * Test the property 'statusReason'
     */
    @Test
    public void statusReasonTest() {
        // TODO: test statusReason
    }

    /**
     * Test the property 'statusReasonDesc'
     */
    @Test
    public void statusReasonDescTest() {
        // TODO: test statusReasonDesc
    }

    /**
     * Test the property 'isPrimary'
     */
    @Test
    public void isPrimaryTest() {
        // TODO: test isPrimary
    }

    /**
     * Test the property 'isPrimaryEffectiveDate'
     */
    @Test
    public void isPrimaryEffectiveDateTest() {
        // TODO: test isPrimaryEffectiveDate
    }

    /**
     * Test the property 'originalHireDate'
     */
    @Test
    public void originalHireDateTest() {
        // TODO: test originalHireDate
    }

}
