/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeePayStatementAccrualsModel
 */
public class EmployeePayStatementAccrualsModelTest {
    private final EmployeePayStatementAccrualsModel model = new EmployeePayStatementAccrualsModel();

    /**
     * Model tests for EmployeePayStatementAccrualsModel
     */
    @Test
    public void testEmployeePayStatementAccrualsModel() {
        // TODO: test EmployeePayStatementAccrualsModel
    }

    /**
     * Test the property 'amountcurrent'
     */
    @Test
    public void amountcurrentTest() {
        // TODO: test amountcurrent
    }

    /**
     * Test the property 'amounttype'
     */
    @Test
    public void amounttypeTest() {
        // TODO: test amounttype
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'plancode'
     */
    @Test
    public void plancodeTest() {
        // TODO: test plancode
    }

    /**
     * Test the property 'plandescription'
     */
    @Test
    public void plandescriptionTest() {
        // TODO: test plandescription
    }

}
