/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NationalDocumentModel
 */
public class NationalDocumentModelTest {
    private final NationalDocumentModel model = new NationalDocumentModel();

    /**
     * Model tests for NationalDocumentModel
     */
    @Test
    public void testNationalDocumentModel() {
        // TODO: test NationalDocumentModel
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'nationalDocumentId'
     */
    @Test
    public void nationalDocumentIdTest() {
        // TODO: test nationalDocumentId
    }

    /**
     * Test the property 'contactId'
     */
    @Test
    public void contactIdTest() {
        // TODO: test contactId
    }

    /**
     * Test the property 'nationalDocumentNumber'
     */
    @Test
    public void nationalDocumentNumberTest() {
        // TODO: test nationalDocumentNumber
    }

    /**
     * Test the property 'nationalDocumentDescription'
     */
    @Test
    public void nationalDocumentDescriptionTest() {
        // TODO: test nationalDocumentDescription
    }

    /**
     * Test the property 'nationalDocumentTypeCode'
     */
    @Test
    public void nationalDocumentTypeCodeTest() {
        // TODO: test nationalDocumentTypeCode
    }

    /**
     * Test the property 'nationalDocumentIssuingCountryCode'
     */
    @Test
    public void nationalDocumentIssuingCountryCodeTest() {
        // TODO: test nationalDocumentIssuingCountryCode
    }

    /**
     * Test the property 'nationalDocumentIssuingPlace'
     */
    @Test
    public void nationalDocumentIssuingPlaceTest() {
        // TODO: test nationalDocumentIssuingPlace
    }

    /**
     * Test the property 'nationalDocumentIssueDate'
     */
    @Test
    public void nationalDocumentIssueDateTest() {
        // TODO: test nationalDocumentIssueDate
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

}
