/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NewHireReadModelCompensation;
import com.konfigthis.client.model.NewHireReadModelContactInformation;
import com.konfigthis.client.model.NewHireReadModelJob;
import com.konfigthis.client.model.NewHireReadModelMentor;
import com.konfigthis.client.model.NewHireReadModelOnboardingOwner;
import com.konfigthis.client.model.NewHireReadModelOrganizationLevelsInner;
import com.konfigthis.client.model.NewHireReadModelProvisioning;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewHireReadModel
 */
public class NewHireReadModelTest {
    private final NewHireReadModel model = new NewHireReadModel();

    /**
     * Model tests for NewHireReadModel
     */
    @Test
    public void testNewHireReadModel() {
        // TODO: test NewHireReadModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'contactInformation'
     */
    @Test
    public void contactInformationTest() {
        // TODO: test contactInformation
    }

    /**
     * Test the property 'job'
     */
    @Test
    public void jobTest() {
        // TODO: test job
    }

    /**
     * Test the property 'organizationLevels'
     */
    @Test
    public void organizationLevelsTest() {
        // TODO: test organizationLevels
    }

    /**
     * Test the property 'compensation'
     */
    @Test
    public void compensationTest() {
        // TODO: test compensation
    }

    /**
     * Test the property 'onboardingOwner'
     */
    @Test
    public void onboardingOwnerTest() {
        // TODO: test onboardingOwner
    }

    /**
     * Test the property 'hireDate'
     */
    @Test
    public void hireDateTest() {
        // TODO: test hireDate
    }

    /**
     * Test the property 'orientationDate'
     */
    @Test
    public void orientationDateTest() {
        // TODO: test orientationDate
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'pastStartDateReason'
     */
    @Test
    public void pastStartDateReasonTest() {
        // TODO: test pastStartDateReason
    }

    /**
     * Test the property 'mentor'
     */
    @Test
    public void mentorTest() {
        // TODO: test mentor
    }

    /**
     * Test the property 'personalMessage'
     */
    @Test
    public void personalMessageTest() {
        // TODO: test personalMessage
    }

    /**
     * Test the property 'provisioning'
     */
    @Test
    public void provisioningTest() {
        // TODO: test provisioning
    }

    /**
     * Test the property 'onboardingStatus'
     */
    @Test
    public void onboardingStatusTest() {
        // TODO: test onboardingStatus
    }

    /**
     * Test the property 'identityUserId'
     */
    @Test
    public void identityUserIdTest() {
        // TODO: test identityUserId
    }

    /**
     * Test the property 'externalUserId'
     */
    @Test
    public void externalUserIdTest() {
        // TODO: test externalUserId
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'sentToProcessHireDate'
     */
    @Test
    public void sentToProcessHireDateTest() {
        // TODO: test sentToProcessHireDate
    }

    /**
     * Test the property 'launchedOn'
     */
    @Test
    public void launchedOnTest() {
        // TODO: test launchedOn
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
