/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NewHiresCreateSingleNewHireResponseJobComponentCompany;
import com.konfigthis.client.model.NewHiresCreateSingleNewHireResponseJobEmployeeType;
import com.konfigthis.client.model.NewHiresCreateSingleNewHireResponseJobSupervisor;
import com.konfigthis.client.model.NewHiresCreateSingleNewHireResponseJobWorkLocation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewHiresCreateSingleNewHireResponseJob
 */
public class NewHiresCreateSingleNewHireResponseJobTest {
    private final NewHiresCreateSingleNewHireResponseJob model = new NewHiresCreateSingleNewHireResponseJob();

    /**
     * Model tests for NewHiresCreateSingleNewHireResponseJob
     */
    @Test
    public void testNewHiresCreateSingleNewHireResponseJob() {
        // TODO: test NewHiresCreateSingleNewHireResponseJob
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'requisitionId'
     */
    @Test
    public void requisitionIdTest() {
        // TODO: test requisitionId
    }

    /**
     * Test the property 'selectedFLSAStatus'
     */
    @Test
    public void selectedFLSAStatusTest() {
        // TODO: test selectedFLSAStatus
    }

    /**
     * Test the property 'componentCompany'
     */
    @Test
    public void componentCompanyTest() {
        // TODO: test componentCompany
    }

    /**
     * Test the property 'workLocation'
     */
    @Test
    public void workLocationTest() {
        // TODO: test workLocation
    }

    /**
     * Test the property 'supervisor'
     */
    @Test
    public void supervisorTest() {
        // TODO: test supervisor
    }

    /**
     * Test the property 'employeeType'
     */
    @Test
    public void employeeTypeTest() {
        // TODO: test employeeType
    }

}
