/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffix
 */
public class NewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffixTest {
    private final NewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffix model = new NewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffix();

    /**
     * Model tests for NewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffix
     */
    @Test
    public void testNewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffix() {
        // TODO: test NewHiresCreateSingleNewHireResponseOnboardingOwnerNameSuffix
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
