/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NewHiresGetByIdResponseProvisioningProvisioningItemsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewHiresGetByIdResponseProvisioning
 */
public class NewHiresGetByIdResponseProvisioningTest {
    private final NewHiresGetByIdResponseProvisioning model = new NewHiresGetByIdResponseProvisioning();

    /**
     * Model tests for NewHiresGetByIdResponseProvisioning
     */
    @Test
    public void testNewHiresGetByIdResponseProvisioning() {
        // TODO: test NewHiresGetByIdResponseProvisioning
    }

    /**
     * Test the property 'provisioningItems'
     */
    @Test
    public void provisioningItemsTest() {
        // TODO: test provisioningItems
    }

    /**
     * Test the property 'summaryEmailRecipients'
     */
    @Test
    public void summaryEmailRecipientsTest() {
        // TODO: test summaryEmailRecipients
    }

}
