/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OpportunityHeadCount
 */
public class OpportunityHeadCountTest {
    private final OpportunityHeadCount model = new OpportunityHeadCount();

    /**
     * Model tests for OpportunityHeadCount
     */
    @Test
    public void testOpportunityHeadCount() {
        // TODO: test OpportunityHeadCount
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'hired'
     */
    @Test
    public void hiredTest() {
        // TODO: test hired
    }

    /**
     * Test the property 'remaining'
     */
    @Test
    public void remainingTest() {
        // TODO: test remaining
    }

}
