/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OpportunityCompenasationCurrency;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OpportunityCompenasation
 */
public class OpportunityCompenasationTest {
    private final OpportunityCompenasation model = new OpportunityCompenasation();

    /**
     * Model tests for OpportunityCompenasation
     */
    @Test
    public void testOpportunityCompenasation() {
        // TODO: test OpportunityCompenasation
    }

    /**
     * Test the property 'isFulltime'
     */
    @Test
    public void isFulltimeTest() {
        // TODO: test isFulltime
    }

    /**
     * Test the property 'isSalaried'
     */
    @Test
    public void isSalariedTest() {
        // TODO: test isSalaried
    }

    /**
     * Test the property 'payRate'
     */
    @Test
    public void payRateTest() {
        // TODO: test payRate
    }

    /**
     * Test the property 'shown'
     */
    @Test
    public void shownTest() {
        // TODO: test shown
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
