/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayrollDeductionsHistory
 */
public class PayrollDeductionsHistoryTest {
    private final PayrollDeductionsHistory model = new PayrollDeductionsHistory();

    /**
     * Model tests for PayrollDeductionsHistory
     */
    @Test
    public void testPayrollDeductionsHistory() {
        // TODO: test PayrollDeductionsHistory
    }

    /**
     * Test the property 'allowPartialDeduction'
     */
    @Test
    public void allowPartialDeductionTest() {
        // TODO: test allowPartialDeduction
    }

    /**
     * Test the property 'batchID'
     */
    @Test
    public void batchIDTest() {
        // TODO: test batchID
    }

    /**
     * Test the property 'benefitAmount'
     */
    @Test
    public void benefitAmountTest() {
        // TODO: test benefitAmount
    }

    /**
     * Test the property 'benefitOption'
     */
    @Test
    public void benefitOptionTest() {
        // TODO: test benefitOption
    }

    /**
     * Test the property 'benefitProvider'
     */
    @Test
    public void benefitProviderTest() {
        // TODO: test benefitProvider
    }

    /**
     * Test the property 'childSupportType'
     */
    @Test
    public void childSupportTypeTest() {
        // TODO: test childSupportType
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'checkId'
     */
    @Test
    public void checkIdTest() {
        // TODO: test checkId
    }

    /**
     * Test the property 'currentArrearsAmount'
     */
    @Test
    public void currentArrearsAmountTest() {
        // TODO: test currentArrearsAmount
    }

    /**
     * Test the property 'customAmount1'
     */
    @Test
    public void customAmount1Test() {
        // TODO: test customAmount1
    }

    /**
     * Test the property 'customAmount2'
     */
    @Test
    public void customAmount2Test() {
        // TODO: test customAmount2
    }

    /**
     * Test the property 'customDate'
     */
    @Test
    public void customDateTest() {
        // TODO: test customDate
    }

    /**
     * Test the property 'deductionCalculationBasisAmt'
     */
    @Test
    public void deductionCalculationBasisAmtTest() {
        // TODO: test deductionCalculationBasisAmt
    }

    /**
     * Test the property 'deductionCode'
     */
    @Test
    public void deductionCodeTest() {
        // TODO: test deductionCode
    }

    /**
     * Test the property 'deductionForBonusOnly'
     */
    @Test
    public void deductionForBonusOnlyTest() {
        // TODO: test deductionForBonusOnly
    }

    /**
     * Test the property 'deductionPlanType'
     */
    @Test
    public void deductionPlanTypeTest() {
        // TODO: test deductionPlanType
    }

    /**
     * Test the property 'deductionType'
     */
    @Test
    public void deductionTypeTest() {
        // TODO: test deductionType
    }

    /**
     * Test the property 'deferredCompensationCap'
     */
    @Test
    public void deferredCompensationCapTest() {
        // TODO: test deferredCompensationCap
    }

    /**
     * Test the property 'deferredCompensationRegularCap'
     */
    @Test
    public void deferredCompensationRegularCapTest() {
        // TODO: test deferredCompensationRegularCap
    }

    /**
     * Test the property 'dependentRecordId'
     */
    @Test
    public void dependentRecordIdTest() {
        // TODO: test dependentRecordId
    }

    /**
     * Test the property 'employeeCalculationRateOrPercent'
     */
    @Test
    public void employeeCalculationRateOrPercentTest() {
        // TODO: test employeeCalculationRateOrPercent
    }

    /**
     * Test the property 'employeeCalculaitonRule'
     */
    @Test
    public void employeeCalculaitonRuleTest() {
        // TODO: test employeeCalculaitonRule
    }

    /**
     * Test the property 'employeeCurrentAmount'
     */
    @Test
    public void employeeCurrentAmountTest() {
        // TODO: test employeeCurrentAmount
    }

    /**
     * Test the property 'employeeDeductionLastPaid'
     */
    @Test
    public void employeeDeductionLastPaidTest() {
        // TODO: test employeeDeductionLastPaid
    }

    /**
     * Test the property 'employeeGoalAmount'
     */
    @Test
    public void employeeGoalAmountTest() {
        // TODO: test employeeGoalAmount
    }

    /**
     * Test the property 'employeeGoalRule'
     */
    @Test
    public void employeeGoalRuleTest() {
        // TODO: test employeeGoalRule
    }

    /**
     * Test the property 'employeeGoalToDateAmount'
     */
    @Test
    public void employeeGoalToDateAmountTest() {
        // TODO: test employeeGoalToDateAmount
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'employeeOriginalAmount'
     */
    @Test
    public void employeeOriginalAmountTest() {
        // TODO: test employeeOriginalAmount
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'employerAnnualCapCalculationRule'
     */
    @Test
    public void employerAnnualCapCalculationRuleTest() {
        // TODO: test employerAnnualCapCalculationRule
    }

    /**
     * Test the property 'employerCalculationRateOrPercent'
     */
    @Test
    public void employerCalculationRateOrPercentTest() {
        // TODO: test employerCalculationRateOrPercent
    }

    /**
     * Test the property 'employerCalculationRule'
     */
    @Test
    public void employerCalculationRuleTest() {
        // TODO: test employerCalculationRule
    }

    /**
     * Test the property 'employerCurrentAmount'
     */
    @Test
    public void employerCurrentAmountTest() {
        // TODO: test employerCurrentAmount
    }

    /**
     * Test the property 'employerPeriodCapCalculationRule'
     */
    @Test
    public void employerPeriodCapCalculationRuleTest() {
        // TODO: test employerPeriodCapCalculationRule
    }

    /**
     * Test the property 'excludeFromWorkersCompensation'
     */
    @Test
    public void excludeFromWorkersCompensationTest() {
        // TODO: test excludeFromWorkersCompensation
    }

    /**
     * Test the property 'generalLedgerExpenseAccount'
     */
    @Test
    public void generalLedgerExpenseAccountTest() {
        // TODO: test generalLedgerExpenseAccount
    }

    /**
     * Test the property 'generalLedgerPayAccount'
     */
    @Test
    public void generalLedgerPayAccountTest() {
        // TODO: test generalLedgerPayAccount
    }

    /**
     * Test the property 'is401k'
     */
    @Test
    public void is401kTest() {
        // TODO: test is401k
    }

    /**
     * Test the property 'is403b'
     */
    @Test
    public void is403bTest() {
        // TODO: test is403b
    }

    /**
     * Test the property 'is408k'
     */
    @Test
    public void is408kTest() {
        // TODO: test is408k
    }

    /**
     * Test the property 'is408p'
     */
    @Test
    public void is408pTest() {
        // TODO: test is408p
    }

    /**
     * Test the property 'is457'
     */
    @Test
    public void is457Test() {
        // TODO: test is457
    }

    /**
     * Test the property 'is457b'
     */
    @Test
    public void is457bTest() {
        // TODO: test is457b
    }

    /**
     * Test the property 'is457F'
     */
    @Test
    public void is457FTest() {
        // TODO: test is457F
    }

    /**
     * Test the property 'is501C'
     */
    @Test
    public void is501CTest() {
        // TODO: test is501C
    }

    /**
     * Test the property 'isD125'
     */
    @Test
    public void isD125Test() {
        // TODO: test isD125
    }

    /**
     * Test the property 'isDeductionOffSet'
     */
    @Test
    public void isDeductionOffSetTest() {
        // TODO: test isDeductionOffSet
    }

    /**
     * Test the property 'isDeferredCompensation'
     */
    @Test
    public void isDeferredCompensationTest() {
        // TODO: test isDeferredCompensation
    }

    /**
     * Test the property 'isDependentCare'
     */
    @Test
    public void isDependentCareTest() {
        // TODO: test isDependentCare
    }

    /**
     * Test the property 'isHousing'
     */
    @Test
    public void isHousingTest() {
        // TODO: test isHousing
    }

    /**
     * Test the property 'isNonQualifiedPlan'
     */
    @Test
    public void isNonQualifiedPlanTest() {
        // TODO: test isNonQualifiedPlan
    }

    /**
     * Test the property 'isPublicEmployeeRetirement'
     */
    @Test
    public void isPublicEmployeeRetirementTest() {
        // TODO: test isPublicEmployeeRetirement
    }

    /**
     * Test the property 'isProrated'
     */
    @Test
    public void isProratedTest() {
        // TODO: test isProrated
    }

    /**
     * Test the property 'isSection125'
     */
    @Test
    public void isSection125Test() {
        // TODO: test isSection125
    }

    /**
     * Test the property 'isVoided'
     */
    @Test
    public void isVoidedTest() {
        // TODO: test isVoided
    }

    /**
     * Test the property 'isVoidingRecord'
     */
    @Test
    public void isVoidingRecordTest() {
        // TODO: test isVoidingRecord
    }

    /**
     * Test the property 'payDate'
     */
    @Test
    public void payDateTest() {
        // TODO: test payDate
    }

    /**
     * Test the property 'payeeID'
     */
    @Test
    public void payeeIDTest() {
        // TODO: test payeeID
    }

    /**
     * Test the property 'payGroup'
     */
    @Test
    public void payGroupTest() {
        // TODO: test payGroup
    }

    /**
     * Test the property 'periodControl'
     */
    @Test
    public void periodControlTest() {
        // TODO: test periodControl
    }

    /**
     * Test the property 'recordId'
     */
    @Test
    public void recordIdTest() {
        // TODO: test recordId
    }

    /**
     * Test the property 'taxCalculationGroupId'
     */
    @Test
    public void taxCalculationGroupIdTest() {
        // TODO: test taxCalculationGroupId
    }

    /**
     * Test the property 'taxCategory'
     */
    @Test
    public void taxCategoryTest() {
        // TODO: test taxCategory
    }

    /**
     * Test the property 'timeclockCode'
     */
    @Test
    public void timeclockCodeTest() {
        // TODO: test timeclockCode
    }

    /**
     * Test the property 'vendor'
     */
    @Test
    public void vendorTest() {
        // TODO: test vendor
    }

    /**
     * Test the property 'wageGarnishmentAdditionalArrearageAmount'
     */
    @Test
    public void wageGarnishmentAdditionalArrearageAmountTest() {
        // TODO: test wageGarnishmentAdditionalArrearageAmount
    }

    /**
     * Test the property 'wageGarnishmentAllocateAsArrears'
     */
    @Test
    public void wageGarnishmentAllocateAsArrearsTest() {
        // TODO: test wageGarnishmentAllocateAsArrears
    }

    /**
     * Test the property 'wageGarnishmentAmountExempt'
     */
    @Test
    public void wageGarnishmentAmountExemptTest() {
        // TODO: test wageGarnishmentAmountExempt
    }

    /**
     * Test the property 'wageGarnishmentAmountExemptFromLevy'
     */
    @Test
    public void wageGarnishmentAmountExemptFromLevyTest() {
        // TODO: test wageGarnishmentAmountExemptFromLevy
    }

    /**
     * Test the property 'wageGarnishmentAmountExemtFromGarn'
     */
    @Test
    public void wageGarnishmentAmountExemtFromGarnTest() {
        // TODO: test wageGarnishmentAmountExemtFromGarn
    }

    /**
     * Test the property 'wageGarnishmentAmountSubjectToCS'
     */
    @Test
    public void wageGarnishmentAmountSubjectToCSTest() {
        // TODO: test wageGarnishmentAmountSubjectToCS
    }

    /**
     * Test the property 'wageGarnishmentAmountSubjectToGarnishment'
     */
    @Test
    public void wageGarnishmentAmountSubjectToGarnishmentTest() {
        // TODO: test wageGarnishmentAmountSubjectToGarnishment
    }

    /**
     * Test the property 'wageGarnishmentDeductionTaxCategory'
     */
    @Test
    public void wageGarnishmentDeductionTaxCategoryTest() {
        // TODO: test wageGarnishmentDeductionTaxCategory
    }

    /**
     * Test the property 'wageGarnishmentDisposableIncome'
     */
    @Test
    public void wageGarnishmentDisposableIncomeTest() {
        // TODO: test wageGarnishmentDisposableIncome
    }

    /**
     * Test the property 'wageGarnishmentMinimumWageFactor'
     */
    @Test
    public void wageGarnishmentMinimumWageFactorTest() {
        // TODO: test wageGarnishmentMinimumWageFactor
    }

    /**
     * Test the property 'wageGarnishmentWageCode'
     */
    @Test
    public void wageGarnishmentWageCodeTest() {
        // TODO: test wageGarnishmentWageCode
    }

    /**
     * Test the property 'yearToDateDeferredCompensationCombinedAmount'
     */
    @Test
    public void yearToDateDeferredCompensationCombinedAmountTest() {
        // TODO: test yearToDateDeferredCompensationCombinedAmount
    }

}
