/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PostingsInnerEducationCriteriaInnerDegree;
import com.konfigthis.client.model.PostingsInnerEducationCriteriaInnerMajor;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostingsInnerEducationCriteriaInner
 */
public class PostingsInnerEducationCriteriaInnerTest {
    private final PostingsInnerEducationCriteriaInner model = new PostingsInnerEducationCriteriaInner();

    /**
     * Model tests for PostingsInnerEducationCriteriaInner
     */
    @Test
    public void testPostingsInnerEducationCriteriaInner() {
        // TODO: test PostingsInnerEducationCriteriaInner
    }

    /**
     * Test the property 'isRequired'
     */
    @Test
    public void isRequiredTest() {
        // TODO: test isRequired
    }

    /**
     * Test the property 'allowRelated'
     */
    @Test
    public void allowRelatedTest() {
        // TODO: test allowRelated
    }

    /**
     * Test the property 'degree'
     */
    @Test
    public void degreeTest() {
        // TODO: test degree
    }

    /**
     * Test the property 'major'
     */
    @Test
    public void majorTest() {
        // TODO: test major
    }

}
