/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PostingsInnerBehaviorCriteriaInner;
import com.konfigthis.client.model.PostingsInnerCompany;
import com.konfigthis.client.model.PostingsInnerDefaultLocale;
import com.konfigthis.client.model.PostingsInnerDescription;
import com.konfigthis.client.model.PostingsInnerEducationCriteriaInner;
import com.konfigthis.client.model.PostingsInnerJobFamily;
import com.konfigthis.client.model.PostingsInnerLicenseCriteriaInner;
import com.konfigthis.client.model.PostingsInnerLinksInner;
import com.konfigthis.client.model.PostingsInnerLocalesInner;
import com.konfigthis.client.model.PostingsInnerLocationsInner;
import com.konfigthis.client.model.PostingsInnerMotivationCriteriaInner;
import com.konfigthis.client.model.PostingsInnerOpportunity;
import com.konfigthis.client.model.PostingsInnerSkillCriteriaInner;
import com.konfigthis.client.model.PostingsInnerTenant;
import com.konfigthis.client.model.PostingsInnerWorkExperienceCriteriaInner;
import com.konfigthis.client.model.Translations;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostingsInner
 */
public class PostingsInnerTest {
    private final PostingsInner model = new PostingsInner();

    /**
     * Model tests for PostingsInner
     */
    @Test
    public void testPostingsInner() {
        // TODO: test PostingsInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tenant'
     */
    @Test
    public void tenantTest() {
        // TODO: test tenant
    }

    /**
     * Test the property 'opportunity'
     */
    @Test
    public void opportunityTest() {
        // TODO: test opportunity
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'requisitionNumber'
     */
    @Test
    public void requisitionNumberTest() {
        // TODO: test requisitionNumber
    }

    /**
     * Test the property 'defaultLocale'
     */
    @Test
    public void defaultLocaleTest() {
        // TODO: test defaultLocale
    }

    /**
     * Test the property 'compensation'
     */
    @Test
    public void compensationTest() {
        // TODO: test compensation
    }

    /**
     * Test the property 'jobFamily'
     */
    @Test
    public void jobFamilyTest() {
        // TODO: test jobFamily
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'locationsSummary'
     */
    @Test
    public void locationsSummaryTest() {
        // TODO: test locationsSummary
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'isFeatured'
     */
    @Test
    public void isFeaturedTest() {
        // TODO: test isFeatured
    }

    /**
     * Test the property 'skillCriteria'
     */
    @Test
    public void skillCriteriaTest() {
        // TODO: test skillCriteria
    }

    /**
     * Test the property 'workExperienceCriteria'
     */
    @Test
    public void workExperienceCriteriaTest() {
        // TODO: test workExperienceCriteria
    }

    /**
     * Test the property 'educationCriteria'
     */
    @Test
    public void educationCriteriaTest() {
        // TODO: test educationCriteria
    }

    /**
     * Test the property 'licenseCriteria'
     */
    @Test
    public void licenseCriteriaTest() {
        // TODO: test licenseCriteria
    }

    /**
     * Test the property 'behaviorCriteria'
     */
    @Test
    public void behaviorCriteriaTest() {
        // TODO: test behaviorCriteria
    }

    /**
     * Test the property 'motivationCriteria'
     */
    @Test
    public void motivationCriteriaTest() {
        // TODO: test motivationCriteria
    }

    /**
     * Test the property 'publishDate'
     */
    @Test
    public void publishDateTest() {
        // TODO: test publishDate
    }

    /**
     * Test the property 'locales'
     */
    @Test
    public void localesTest() {
        // TODO: test locales
    }

    /**
     * Test the property 'recruitingApplyUrl'
     */
    @Test
    public void recruitingApplyUrlTest() {
        // TODO: test recruitingApplyUrl
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
