/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * EarningsDto
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EarningsDto {
  public static final String SERIALIZED_NAME_EARNING_CODE = "earningCode";
  @SerializedName(SERIALIZED_NAME_EARNING_CODE)
  private String earningCode;

  public static final String SERIALIZED_NAME_LONG_DESCRIPTION = "longDescription";
  @SerializedName(SERIALIZED_NAME_LONG_DESCRIPTION)
  private String longDescription;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Double amount;

  public static final String SERIALIZED_NAME_BLOCK_FEDERAL_INCOME_TAX = "blockFederalIncomeTax";
  @SerializedName(SERIALIZED_NAME_BLOCK_FEDERAL_INCOME_TAX)
  private Boolean blockFederalIncomeTax;

  public static final String SERIALIZED_NAME_BLOCK_LOCAL_INCOME_TAX = "blockLocalIncomeTax";
  @SerializedName(SERIALIZED_NAME_BLOCK_LOCAL_INCOME_TAX)
  private Boolean blockLocalIncomeTax;

  public static final String SERIALIZED_NAME_BLOCK_STATE_INCOME_TAX = "blockStateIncomeTax";
  @SerializedName(SERIALIZED_NAME_BLOCK_STATE_INCOME_TAX)
  private Boolean blockStateIncomeTax;

  public static final String SERIALIZED_NAME_CALCULATION_RULE = "calculationRule";
  @SerializedName(SERIALIZED_NAME_CALCULATION_RULE)
  private String calculationRule;

  public static final String SERIALIZED_NAME_DISPLAY_IN_PAY_DATA_ENTRY = "displayInPayDataEntry";
  @SerializedName(SERIALIZED_NAME_DISPLAY_IN_PAY_DATA_ENTRY)
  private Boolean displayInPayDataEntry;

  public static final String SERIALIZED_NAME_EXCEL_IN_TOTAL_HOURS = "excelInTotalHours";
  @SerializedName(SERIALIZED_NAME_EXCEL_IN_TOTAL_HOURS)
  private Boolean excelInTotalHours;

  public static final String SERIALIZED_NAME_FLAT_HOURS = "flatHours";
  @SerializedName(SERIALIZED_NAME_FLAT_HOURS)
  private Double flatHours;

  public static final String SERIALIZED_NAME_INCLUDE_IN_ACCRUALS = "includeInAccruals";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_ACCRUALS)
  private String includeInAccruals;

  public static final String SERIALIZED_NAME_INCLUDE_IN_ALLOCATIONS = "includeInAllocations";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_ALLOCATIONS)
  private Boolean includeInAllocations;

  public static final String SERIALIZED_NAME_INCLUDE_FLSA_AVERAGE_PAY_RATE = "includeFlsaAveragePayRate";
  @SerializedName(SERIALIZED_NAME_INCLUDE_FLSA_AVERAGE_PAY_RATE)
  private Boolean includeFlsaAveragePayRate;

  public static final String SERIALIZED_NAME_INCLUDE_IN_BENEFIT_HOURS = "includeInBenefitHours";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_BENEFIT_HOURS)
  private Boolean includeInBenefitHours;

  public static final String SERIALIZED_NAME_INCLUDE_IN_DEFERRED_COMPENSATION = "includeInDeferredCompensation";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_DEFERRED_COMPENSATION)
  private Boolean includeInDeferredCompensation;

  public static final String SERIALIZED_NAME_INCLUDE_IN_DEFERRED_COMPENSATION_HOURS = "includeInDeferredCompensationHours";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_DEFERRED_COMPENSATION_HOURS)
  private Boolean includeInDeferredCompensationHours;

  public static final String SERIALIZED_NAME_INCLUDE_IN_EARNING_ACCUMULATION = "includeInEarningAccumulation";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_EARNING_ACCUMULATION)
  private Boolean includeInEarningAccumulation;

  public static final String SERIALIZED_NAME_INCLUDE_IN_HOURS_ACCUMULATION = "includeInHoursAccumulation";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_HOURS_ACCUMULATION)
  private Boolean includeInHoursAccumulation;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MANUAL_CHECK = "includeInManualCheck";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MANUAL_CHECK)
  private Boolean includeInManualCheck;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING1 = "includeInMiscellaneousEarning1";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING1)
  private Boolean includeInMiscellaneousEarning1;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING2 = "includeInMiscellaneousEarning2";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING2)
  private Boolean includeInMiscellaneousEarning2;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING3 = "includeInMiscellaneousEarning3";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING3)
  private Boolean includeInMiscellaneousEarning3;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING4 = "includeInMiscellaneousEarning4";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING4)
  private Boolean includeInMiscellaneousEarning4;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING5 = "includeInMiscellaneousEarning5";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING5)
  private Boolean includeInMiscellaneousEarning5;

  public static final String SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING6 = "includeInMiscellaneousEarning6";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_MISCELLANEOUS_EARNING6)
  private Boolean includeInMiscellaneousEarning6;

  public static final String SERIALIZED_NAME_INCLUDE_IN_PENSION_ACCUMULATION = "includeInPensionAccumulation";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_PENSION_ACCUMULATION)
  private Boolean includeInPensionAccumulation;

  public static final String SERIALIZED_NAME_INCLUDE_IN_RETRO_PAY = "includeInRetroPay";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_RETRO_PAY)
  private Boolean includeInRetroPay;

  public static final String SERIALIZED_NAME_INCLUDE_IN_SHIFT_DIFFRENTIAL = "includeInShiftDiffrential";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_SHIFT_DIFFRENTIAL)
  private Boolean includeInShiftDiffrential;

  public static final String SERIALIZED_NAME_IS_PRODUCTIVE_TIME = "isProductiveTime";
  @SerializedName(SERIALIZED_NAME_IS_PRODUCTIVE_TIME)
  private Boolean isProductiveTime;

  public static final String SERIALIZED_NAME_IS_SUPPLIMENTAL_WAGES = "isSupplimentalWages";
  @SerializedName(SERIALIZED_NAME_IS_SUPPLIMENTAL_WAGES)
  private Boolean isSupplimentalWages;

  public static final String SERIALIZED_NAME_MONTHLY_PAY_PERIOD1 = "monthlyPayPeriod1";
  @SerializedName(SERIALIZED_NAME_MONTHLY_PAY_PERIOD1)
  private Boolean monthlyPayPeriod1;

  public static final String SERIALIZED_NAME_MONTHLY_PAY_PERIOD2 = "monthlyPayPeriod2";
  @SerializedName(SERIALIZED_NAME_MONTHLY_PAY_PERIOD2)
  private Boolean monthlyPayPeriod2;

  public static final String SERIALIZED_NAME_MONTHLY_PAY_PERIOD3 = "monthlyPayPeriod3";
  @SerializedName(SERIALIZED_NAME_MONTHLY_PAY_PERIOD3)
  private Boolean monthlyPayPeriod3;

  public static final String SERIALIZED_NAME_MONTHLY_PAY_PERIOD4 = "monthlyPayPeriod4";
  @SerializedName(SERIALIZED_NAME_MONTHLY_PAY_PERIOD4)
  private Boolean monthlyPayPeriod4;

  public static final String SERIALIZED_NAME_MONTHLY_PAY_PERIOD5 = "monthlyPayPeriod5";
  @SerializedName(SERIALIZED_NAME_MONTHLY_PAY_PERIOD5)
  private Boolean monthlyPayPeriod5;

  public static final String SERIALIZED_NAME_NOTES = "notes";
  @SerializedName(SERIALIZED_NAME_NOTES)
  private String notes;

  public static final String SERIALIZED_NAME_REDUCE_REGULAR_DOLLARS = "reduceRegularDollars";
  @SerializedName(SERIALIZED_NAME_REDUCE_REGULAR_DOLLARS)
  private Boolean reduceRegularDollars;

  public static final String SERIALIZED_NAME_REDUCE_REGULAR_HOURS = "reduceRegularHours";
  @SerializedName(SERIALIZED_NAME_REDUCE_REGULAR_HOURS)
  private Boolean reduceRegularHours;

  public static final String SERIALIZED_NAME_REPORT_CATEGORY = "reportCategory";
  @SerializedName(SERIALIZED_NAME_REPORT_CATEGORY)
  private String reportCategory;

  public static final String SERIALIZED_NAME_SCHEDULE_SUPPLEMENTAL = "scheduleSupplemental";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_SUPPLEMENTAL)
  private Boolean scheduleSupplemental;

  public static final String SERIALIZED_NAME_STUB_DESCRIPTION = "stubDescription";
  @SerializedName(SERIALIZED_NAME_STUB_DESCRIPTION)
  private String stubDescription;

  public static final String SERIALIZED_NAME_TAX_CATEGORY = "taxCategory";
  @SerializedName(SERIALIZED_NAME_TAX_CATEGORY)
  private String taxCategory;

  public static final String SERIALIZED_NAME_TIME_CLOCK_CODE = "timeClockCode";
  @SerializedName(SERIALIZED_NAME_TIME_CLOCK_CODE)
  private String timeClockCode;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_USE_DEDUCTION_OFFSET = "useDeductionOffset";
  @SerializedName(SERIALIZED_NAME_USE_DEDUCTION_OFFSET)
  private Boolean useDeductionOffset;

  public static final String SERIALIZED_NAME_INCLUDE_IN_REGISTERED_PENSION_PLAN = "includeInRegisteredPensionPlan";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_REGISTERED_PENSION_PLAN)
  private Boolean includeInRegisteredPensionPlan;

  public static final String SERIALIZED_NAME_INCLUDE_IN_REGISTERED_RETIREMENT_SAVINGS_PLAN = "includeInRegisteredRetirementSavingsPlan";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_REGISTERED_RETIREMENT_SAVINGS_PLAN)
  private Boolean includeInRegisteredRetirementSavingsPlan;

  public static final String SERIALIZED_NAME_INCLUDE_IN_UNION_DUES = "includeInUnionDues";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_UNION_DUES)
  private Boolean includeInUnionDues;

  public static final String SERIALIZED_NAME_INCLUDE_IN_UNION_DUES_HOURS = "includeInUnionDuesHours";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_UNION_DUES_HOURS)
  private Boolean includeInUnionDuesHours;

  public static final String SERIALIZED_NAME_TAX_CALCULATION_RULE = "taxCalculationRule";
  @SerializedName(SERIALIZED_NAME_TAX_CALCULATION_RULE)
  private String taxCalculationRule;

  public static final String SERIALIZED_NAME_EXEMPT_FROM_EARNED_INCOME_HOURS = "exemptFromEarnedIncomeHours";
  @SerializedName(SERIALIZED_NAME_EXEMPT_FROM_EARNED_INCOME_HOURS)
  private String exemptFromEarnedIncomeHours;

  public static final String SERIALIZED_NAME_INCLUDE_IN_HEALTH_CARE_HOURS = "includeInHealthCareHours";
  @SerializedName(SERIALIZED_NAME_INCLUDE_IN_HEALTH_CARE_HOURS)
  private Boolean includeInHealthCareHours;

  public static final String SERIALIZED_NAME_VERIFICATION_TYPE_CODE = "verificationTypeCode";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_TYPE_CODE)
  private String verificationTypeCode;

  public static final String SERIALIZED_NAME_VERIFICATION_TYPE_DESCRIPTION = "verificationTypeDescription";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_TYPE_DESCRIPTION)
  private String verificationTypeDescription;

  public EarningsDto() {
  }

  public EarningsDto earningCode(String earningCode) {
    
    
    
    
    this.earningCode = earningCode;
    return this;
  }

   /**
   * Get earningCode
   * @return earningCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getEarningCode() {
    return earningCode;
  }


  public void setEarningCode(String earningCode) {
    
    
    
    this.earningCode = earningCode;
  }


  public EarningsDto longDescription(String longDescription) {
    
    
    
    
    this.longDescription = longDescription;
    return this;
  }

   /**
   * Get longDescription
   * @return longDescription
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLongDescription() {
    return longDescription;
  }


  public void setLongDescription(String longDescription) {
    
    
    
    this.longDescription = longDescription;
  }


  public EarningsDto amount(Double amount) {
    
    
    
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAmount() {
    return amount;
  }


  public void setAmount(Double amount) {
    
    
    
    this.amount = amount;
  }


  public EarningsDto blockFederalIncomeTax(Boolean blockFederalIncomeTax) {
    
    
    
    
    this.blockFederalIncomeTax = blockFederalIncomeTax;
    return this;
  }

   /**
   * Get blockFederalIncomeTax
   * @return blockFederalIncomeTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getBlockFederalIncomeTax() {
    return blockFederalIncomeTax;
  }


  public void setBlockFederalIncomeTax(Boolean blockFederalIncomeTax) {
    
    
    
    this.blockFederalIncomeTax = blockFederalIncomeTax;
  }


  public EarningsDto blockLocalIncomeTax(Boolean blockLocalIncomeTax) {
    
    
    
    
    this.blockLocalIncomeTax = blockLocalIncomeTax;
    return this;
  }

   /**
   * Get blockLocalIncomeTax
   * @return blockLocalIncomeTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getBlockLocalIncomeTax() {
    return blockLocalIncomeTax;
  }


  public void setBlockLocalIncomeTax(Boolean blockLocalIncomeTax) {
    
    
    
    this.blockLocalIncomeTax = blockLocalIncomeTax;
  }


  public EarningsDto blockStateIncomeTax(Boolean blockStateIncomeTax) {
    
    
    
    
    this.blockStateIncomeTax = blockStateIncomeTax;
    return this;
  }

   /**
   * Get blockStateIncomeTax
   * @return blockStateIncomeTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getBlockStateIncomeTax() {
    return blockStateIncomeTax;
  }


  public void setBlockStateIncomeTax(Boolean blockStateIncomeTax) {
    
    
    
    this.blockStateIncomeTax = blockStateIncomeTax;
  }


  public EarningsDto calculationRule(String calculationRule) {
    
    
    
    
    this.calculationRule = calculationRule;
    return this;
  }

   /**
   * Get calculationRule
   * @return calculationRule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCalculationRule() {
    return calculationRule;
  }


  public void setCalculationRule(String calculationRule) {
    
    
    
    this.calculationRule = calculationRule;
  }


  public EarningsDto displayInPayDataEntry(Boolean displayInPayDataEntry) {
    
    
    
    
    this.displayInPayDataEntry = displayInPayDataEntry;
    return this;
  }

   /**
   * Get displayInPayDataEntry
   * @return displayInPayDataEntry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDisplayInPayDataEntry() {
    return displayInPayDataEntry;
  }


  public void setDisplayInPayDataEntry(Boolean displayInPayDataEntry) {
    
    
    
    this.displayInPayDataEntry = displayInPayDataEntry;
  }


  public EarningsDto excelInTotalHours(Boolean excelInTotalHours) {
    
    
    
    
    this.excelInTotalHours = excelInTotalHours;
    return this;
  }

   /**
   * Get excelInTotalHours
   * @return excelInTotalHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getExcelInTotalHours() {
    return excelInTotalHours;
  }


  public void setExcelInTotalHours(Boolean excelInTotalHours) {
    
    
    
    this.excelInTotalHours = excelInTotalHours;
  }


  public EarningsDto flatHours(Double flatHours) {
    
    
    
    
    this.flatHours = flatHours;
    return this;
  }

   /**
   * Get flatHours
   * @return flatHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getFlatHours() {
    return flatHours;
  }


  public void setFlatHours(Double flatHours) {
    
    
    
    this.flatHours = flatHours;
  }


  public EarningsDto includeInAccruals(String includeInAccruals) {
    
    
    
    
    this.includeInAccruals = includeInAccruals;
    return this;
  }

   /**
   * Get includeInAccruals
   * @return includeInAccruals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIncludeInAccruals() {
    return includeInAccruals;
  }


  public void setIncludeInAccruals(String includeInAccruals) {
    
    
    
    this.includeInAccruals = includeInAccruals;
  }


  public EarningsDto includeInAllocations(Boolean includeInAllocations) {
    
    
    
    
    this.includeInAllocations = includeInAllocations;
    return this;
  }

   /**
   * Get includeInAllocations
   * @return includeInAllocations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInAllocations() {
    return includeInAllocations;
  }


  public void setIncludeInAllocations(Boolean includeInAllocations) {
    
    
    
    this.includeInAllocations = includeInAllocations;
  }


  public EarningsDto includeFlsaAveragePayRate(Boolean includeFlsaAveragePayRate) {
    
    
    
    
    this.includeFlsaAveragePayRate = includeFlsaAveragePayRate;
    return this;
  }

   /**
   * Get includeFlsaAveragePayRate
   * @return includeFlsaAveragePayRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeFlsaAveragePayRate() {
    return includeFlsaAveragePayRate;
  }


  public void setIncludeFlsaAveragePayRate(Boolean includeFlsaAveragePayRate) {
    
    
    
    this.includeFlsaAveragePayRate = includeFlsaAveragePayRate;
  }


  public EarningsDto includeInBenefitHours(Boolean includeInBenefitHours) {
    
    
    
    
    this.includeInBenefitHours = includeInBenefitHours;
    return this;
  }

   /**
   * Get includeInBenefitHours
   * @return includeInBenefitHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInBenefitHours() {
    return includeInBenefitHours;
  }


  public void setIncludeInBenefitHours(Boolean includeInBenefitHours) {
    
    
    
    this.includeInBenefitHours = includeInBenefitHours;
  }


  public EarningsDto includeInDeferredCompensation(Boolean includeInDeferredCompensation) {
    
    
    
    
    this.includeInDeferredCompensation = includeInDeferredCompensation;
    return this;
  }

   /**
   * Get includeInDeferredCompensation
   * @return includeInDeferredCompensation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInDeferredCompensation() {
    return includeInDeferredCompensation;
  }


  public void setIncludeInDeferredCompensation(Boolean includeInDeferredCompensation) {
    
    
    
    this.includeInDeferredCompensation = includeInDeferredCompensation;
  }


  public EarningsDto includeInDeferredCompensationHours(Boolean includeInDeferredCompensationHours) {
    
    
    
    
    this.includeInDeferredCompensationHours = includeInDeferredCompensationHours;
    return this;
  }

   /**
   * Get includeInDeferredCompensationHours
   * @return includeInDeferredCompensationHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInDeferredCompensationHours() {
    return includeInDeferredCompensationHours;
  }


  public void setIncludeInDeferredCompensationHours(Boolean includeInDeferredCompensationHours) {
    
    
    
    this.includeInDeferredCompensationHours = includeInDeferredCompensationHours;
  }


  public EarningsDto includeInEarningAccumulation(Boolean includeInEarningAccumulation) {
    
    
    
    
    this.includeInEarningAccumulation = includeInEarningAccumulation;
    return this;
  }

   /**
   * Get includeInEarningAccumulation
   * @return includeInEarningAccumulation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInEarningAccumulation() {
    return includeInEarningAccumulation;
  }


  public void setIncludeInEarningAccumulation(Boolean includeInEarningAccumulation) {
    
    
    
    this.includeInEarningAccumulation = includeInEarningAccumulation;
  }


  public EarningsDto includeInHoursAccumulation(Boolean includeInHoursAccumulation) {
    
    
    
    
    this.includeInHoursAccumulation = includeInHoursAccumulation;
    return this;
  }

   /**
   * Get includeInHoursAccumulation
   * @return includeInHoursAccumulation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInHoursAccumulation() {
    return includeInHoursAccumulation;
  }


  public void setIncludeInHoursAccumulation(Boolean includeInHoursAccumulation) {
    
    
    
    this.includeInHoursAccumulation = includeInHoursAccumulation;
  }


  public EarningsDto includeInManualCheck(Boolean includeInManualCheck) {
    
    
    
    
    this.includeInManualCheck = includeInManualCheck;
    return this;
  }

   /**
   * Get includeInManualCheck
   * @return includeInManualCheck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInManualCheck() {
    return includeInManualCheck;
  }


  public void setIncludeInManualCheck(Boolean includeInManualCheck) {
    
    
    
    this.includeInManualCheck = includeInManualCheck;
  }


  public EarningsDto includeInMiscellaneousEarning1(Boolean includeInMiscellaneousEarning1) {
    
    
    
    
    this.includeInMiscellaneousEarning1 = includeInMiscellaneousEarning1;
    return this;
  }

   /**
   * Get includeInMiscellaneousEarning1
   * @return includeInMiscellaneousEarning1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInMiscellaneousEarning1() {
    return includeInMiscellaneousEarning1;
  }


  public void setIncludeInMiscellaneousEarning1(Boolean includeInMiscellaneousEarning1) {
    
    
    
    this.includeInMiscellaneousEarning1 = includeInMiscellaneousEarning1;
  }


  public EarningsDto includeInMiscellaneousEarning2(Boolean includeInMiscellaneousEarning2) {
    
    
    
    
    this.includeInMiscellaneousEarning2 = includeInMiscellaneousEarning2;
    return this;
  }

   /**
   * Get includeInMiscellaneousEarning2
   * @return includeInMiscellaneousEarning2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInMiscellaneousEarning2() {
    return includeInMiscellaneousEarning2;
  }


  public void setIncludeInMiscellaneousEarning2(Boolean includeInMiscellaneousEarning2) {
    
    
    
    this.includeInMiscellaneousEarning2 = includeInMiscellaneousEarning2;
  }


  public EarningsDto includeInMiscellaneousEarning3(Boolean includeInMiscellaneousEarning3) {
    
    
    
    
    this.includeInMiscellaneousEarning3 = includeInMiscellaneousEarning3;
    return this;
  }

   /**
   * Get includeInMiscellaneousEarning3
   * @return includeInMiscellaneousEarning3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInMiscellaneousEarning3() {
    return includeInMiscellaneousEarning3;
  }


  public void setIncludeInMiscellaneousEarning3(Boolean includeInMiscellaneousEarning3) {
    
    
    
    this.includeInMiscellaneousEarning3 = includeInMiscellaneousEarning3;
  }


  public EarningsDto includeInMiscellaneousEarning4(Boolean includeInMiscellaneousEarning4) {
    
    
    
    
    this.includeInMiscellaneousEarning4 = includeInMiscellaneousEarning4;
    return this;
  }

   /**
   * Get includeInMiscellaneousEarning4
   * @return includeInMiscellaneousEarning4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInMiscellaneousEarning4() {
    return includeInMiscellaneousEarning4;
  }


  public void setIncludeInMiscellaneousEarning4(Boolean includeInMiscellaneousEarning4) {
    
    
    
    this.includeInMiscellaneousEarning4 = includeInMiscellaneousEarning4;
  }


  public EarningsDto includeInMiscellaneousEarning5(Boolean includeInMiscellaneousEarning5) {
    
    
    
    
    this.includeInMiscellaneousEarning5 = includeInMiscellaneousEarning5;
    return this;
  }

   /**
   * Get includeInMiscellaneousEarning5
   * @return includeInMiscellaneousEarning5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInMiscellaneousEarning5() {
    return includeInMiscellaneousEarning5;
  }


  public void setIncludeInMiscellaneousEarning5(Boolean includeInMiscellaneousEarning5) {
    
    
    
    this.includeInMiscellaneousEarning5 = includeInMiscellaneousEarning5;
  }


  public EarningsDto includeInMiscellaneousEarning6(Boolean includeInMiscellaneousEarning6) {
    
    
    
    
    this.includeInMiscellaneousEarning6 = includeInMiscellaneousEarning6;
    return this;
  }

   /**
   * Get includeInMiscellaneousEarning6
   * @return includeInMiscellaneousEarning6
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInMiscellaneousEarning6() {
    return includeInMiscellaneousEarning6;
  }


  public void setIncludeInMiscellaneousEarning6(Boolean includeInMiscellaneousEarning6) {
    
    
    
    this.includeInMiscellaneousEarning6 = includeInMiscellaneousEarning6;
  }


  public EarningsDto includeInPensionAccumulation(Boolean includeInPensionAccumulation) {
    
    
    
    
    this.includeInPensionAccumulation = includeInPensionAccumulation;
    return this;
  }

   /**
   * Get includeInPensionAccumulation
   * @return includeInPensionAccumulation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInPensionAccumulation() {
    return includeInPensionAccumulation;
  }


  public void setIncludeInPensionAccumulation(Boolean includeInPensionAccumulation) {
    
    
    
    this.includeInPensionAccumulation = includeInPensionAccumulation;
  }


  public EarningsDto includeInRetroPay(Boolean includeInRetroPay) {
    
    
    
    
    this.includeInRetroPay = includeInRetroPay;
    return this;
  }

   /**
   * Get includeInRetroPay
   * @return includeInRetroPay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInRetroPay() {
    return includeInRetroPay;
  }


  public void setIncludeInRetroPay(Boolean includeInRetroPay) {
    
    
    
    this.includeInRetroPay = includeInRetroPay;
  }


  public EarningsDto includeInShiftDiffrential(Boolean includeInShiftDiffrential) {
    
    
    
    
    this.includeInShiftDiffrential = includeInShiftDiffrential;
    return this;
  }

   /**
   * Get includeInShiftDiffrential
   * @return includeInShiftDiffrential
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInShiftDiffrential() {
    return includeInShiftDiffrential;
  }


  public void setIncludeInShiftDiffrential(Boolean includeInShiftDiffrential) {
    
    
    
    this.includeInShiftDiffrential = includeInShiftDiffrential;
  }


  public EarningsDto isProductiveTime(Boolean isProductiveTime) {
    
    
    
    
    this.isProductiveTime = isProductiveTime;
    return this;
  }

   /**
   * Get isProductiveTime
   * @return isProductiveTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsProductiveTime() {
    return isProductiveTime;
  }


  public void setIsProductiveTime(Boolean isProductiveTime) {
    
    
    
    this.isProductiveTime = isProductiveTime;
  }


  public EarningsDto isSupplimentalWages(Boolean isSupplimentalWages) {
    
    
    
    
    this.isSupplimentalWages = isSupplimentalWages;
    return this;
  }

   /**
   * Get isSupplimentalWages
   * @return isSupplimentalWages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsSupplimentalWages() {
    return isSupplimentalWages;
  }


  public void setIsSupplimentalWages(Boolean isSupplimentalWages) {
    
    
    
    this.isSupplimentalWages = isSupplimentalWages;
  }


  public EarningsDto monthlyPayPeriod1(Boolean monthlyPayPeriod1) {
    
    
    
    
    this.monthlyPayPeriod1 = monthlyPayPeriod1;
    return this;
  }

   /**
   * Get monthlyPayPeriod1
   * @return monthlyPayPeriod1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMonthlyPayPeriod1() {
    return monthlyPayPeriod1;
  }


  public void setMonthlyPayPeriod1(Boolean monthlyPayPeriod1) {
    
    
    
    this.monthlyPayPeriod1 = monthlyPayPeriod1;
  }


  public EarningsDto monthlyPayPeriod2(Boolean monthlyPayPeriod2) {
    
    
    
    
    this.monthlyPayPeriod2 = monthlyPayPeriod2;
    return this;
  }

   /**
   * Get monthlyPayPeriod2
   * @return monthlyPayPeriod2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMonthlyPayPeriod2() {
    return monthlyPayPeriod2;
  }


  public void setMonthlyPayPeriod2(Boolean monthlyPayPeriod2) {
    
    
    
    this.monthlyPayPeriod2 = monthlyPayPeriod2;
  }


  public EarningsDto monthlyPayPeriod3(Boolean monthlyPayPeriod3) {
    
    
    
    
    this.monthlyPayPeriod3 = monthlyPayPeriod3;
    return this;
  }

   /**
   * Get monthlyPayPeriod3
   * @return monthlyPayPeriod3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMonthlyPayPeriod3() {
    return monthlyPayPeriod3;
  }


  public void setMonthlyPayPeriod3(Boolean monthlyPayPeriod3) {
    
    
    
    this.monthlyPayPeriod3 = monthlyPayPeriod3;
  }


  public EarningsDto monthlyPayPeriod4(Boolean monthlyPayPeriod4) {
    
    
    
    
    this.monthlyPayPeriod4 = monthlyPayPeriod4;
    return this;
  }

   /**
   * Get monthlyPayPeriod4
   * @return monthlyPayPeriod4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMonthlyPayPeriod4() {
    return monthlyPayPeriod4;
  }


  public void setMonthlyPayPeriod4(Boolean monthlyPayPeriod4) {
    
    
    
    this.monthlyPayPeriod4 = monthlyPayPeriod4;
  }


  public EarningsDto monthlyPayPeriod5(Boolean monthlyPayPeriod5) {
    
    
    
    
    this.monthlyPayPeriod5 = monthlyPayPeriod5;
    return this;
  }

   /**
   * Get monthlyPayPeriod5
   * @return monthlyPayPeriod5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMonthlyPayPeriod5() {
    return monthlyPayPeriod5;
  }


  public void setMonthlyPayPeriod5(Boolean monthlyPayPeriod5) {
    
    
    
    this.monthlyPayPeriod5 = monthlyPayPeriod5;
  }


  public EarningsDto notes(String notes) {
    
    
    
    
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNotes() {
    return notes;
  }


  public void setNotes(String notes) {
    
    
    
    this.notes = notes;
  }


  public EarningsDto reduceRegularDollars(Boolean reduceRegularDollars) {
    
    
    
    
    this.reduceRegularDollars = reduceRegularDollars;
    return this;
  }

   /**
   * Get reduceRegularDollars
   * @return reduceRegularDollars
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReduceRegularDollars() {
    return reduceRegularDollars;
  }


  public void setReduceRegularDollars(Boolean reduceRegularDollars) {
    
    
    
    this.reduceRegularDollars = reduceRegularDollars;
  }


  public EarningsDto reduceRegularHours(Boolean reduceRegularHours) {
    
    
    
    
    this.reduceRegularHours = reduceRegularHours;
    return this;
  }

   /**
   * Get reduceRegularHours
   * @return reduceRegularHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReduceRegularHours() {
    return reduceRegularHours;
  }


  public void setReduceRegularHours(Boolean reduceRegularHours) {
    
    
    
    this.reduceRegularHours = reduceRegularHours;
  }


  public EarningsDto reportCategory(String reportCategory) {
    
    
    
    
    this.reportCategory = reportCategory;
    return this;
  }

   /**
   * Get reportCategory
   * @return reportCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReportCategory() {
    return reportCategory;
  }


  public void setReportCategory(String reportCategory) {
    
    
    
    this.reportCategory = reportCategory;
  }


  public EarningsDto scheduleSupplemental(Boolean scheduleSupplemental) {
    
    
    
    
    this.scheduleSupplemental = scheduleSupplemental;
    return this;
  }

   /**
   * Get scheduleSupplemental
   * @return scheduleSupplemental
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getScheduleSupplemental() {
    return scheduleSupplemental;
  }


  public void setScheduleSupplemental(Boolean scheduleSupplemental) {
    
    
    
    this.scheduleSupplemental = scheduleSupplemental;
  }


  public EarningsDto stubDescription(String stubDescription) {
    
    
    
    
    this.stubDescription = stubDescription;
    return this;
  }

   /**
   * Get stubDescription
   * @return stubDescription
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getStubDescription() {
    return stubDescription;
  }


  public void setStubDescription(String stubDescription) {
    
    
    
    this.stubDescription = stubDescription;
  }


  public EarningsDto taxCategory(String taxCategory) {
    
    
    
    
    this.taxCategory = taxCategory;
    return this;
  }

   /**
   * Get taxCategory
   * @return taxCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTaxCategory() {
    return taxCategory;
  }


  public void setTaxCategory(String taxCategory) {
    
    
    
    this.taxCategory = taxCategory;
  }


  public EarningsDto timeClockCode(String timeClockCode) {
    
    
    
    
    this.timeClockCode = timeClockCode;
    return this;
  }

   /**
   * Get timeClockCode
   * @return timeClockCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getTimeClockCode() {
    return timeClockCode;
  }


  public void setTimeClockCode(String timeClockCode) {
    
    
    
    this.timeClockCode = timeClockCode;
  }


  public EarningsDto countryCode(String countryCode) {
    
    
    
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    
    
    
    this.countryCode = countryCode;
  }


  public EarningsDto useDeductionOffset(Boolean useDeductionOffset) {
    
    
    
    
    this.useDeductionOffset = useDeductionOffset;
    return this;
  }

   /**
   * Get useDeductionOffset
   * @return useDeductionOffset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getUseDeductionOffset() {
    return useDeductionOffset;
  }


  public void setUseDeductionOffset(Boolean useDeductionOffset) {
    
    
    
    this.useDeductionOffset = useDeductionOffset;
  }


  public EarningsDto includeInRegisteredPensionPlan(Boolean includeInRegisteredPensionPlan) {
    
    
    
    
    this.includeInRegisteredPensionPlan = includeInRegisteredPensionPlan;
    return this;
  }

   /**
   * Get includeInRegisteredPensionPlan
   * @return includeInRegisteredPensionPlan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInRegisteredPensionPlan() {
    return includeInRegisteredPensionPlan;
  }


  public void setIncludeInRegisteredPensionPlan(Boolean includeInRegisteredPensionPlan) {
    
    
    
    this.includeInRegisteredPensionPlan = includeInRegisteredPensionPlan;
  }


  public EarningsDto includeInRegisteredRetirementSavingsPlan(Boolean includeInRegisteredRetirementSavingsPlan) {
    
    
    
    
    this.includeInRegisteredRetirementSavingsPlan = includeInRegisteredRetirementSavingsPlan;
    return this;
  }

   /**
   * Get includeInRegisteredRetirementSavingsPlan
   * @return includeInRegisteredRetirementSavingsPlan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInRegisteredRetirementSavingsPlan() {
    return includeInRegisteredRetirementSavingsPlan;
  }


  public void setIncludeInRegisteredRetirementSavingsPlan(Boolean includeInRegisteredRetirementSavingsPlan) {
    
    
    
    this.includeInRegisteredRetirementSavingsPlan = includeInRegisteredRetirementSavingsPlan;
  }


  public EarningsDto includeInUnionDues(Boolean includeInUnionDues) {
    
    
    
    
    this.includeInUnionDues = includeInUnionDues;
    return this;
  }

   /**
   * Get includeInUnionDues
   * @return includeInUnionDues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInUnionDues() {
    return includeInUnionDues;
  }


  public void setIncludeInUnionDues(Boolean includeInUnionDues) {
    
    
    
    this.includeInUnionDues = includeInUnionDues;
  }


  public EarningsDto includeInUnionDuesHours(Boolean includeInUnionDuesHours) {
    
    
    
    
    this.includeInUnionDuesHours = includeInUnionDuesHours;
    return this;
  }

   /**
   * Get includeInUnionDuesHours
   * @return includeInUnionDuesHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInUnionDuesHours() {
    return includeInUnionDuesHours;
  }


  public void setIncludeInUnionDuesHours(Boolean includeInUnionDuesHours) {
    
    
    
    this.includeInUnionDuesHours = includeInUnionDuesHours;
  }


  public EarningsDto taxCalculationRule(String taxCalculationRule) {
    
    
    
    
    this.taxCalculationRule = taxCalculationRule;
    return this;
  }

   /**
   * Get taxCalculationRule
   * @return taxCalculationRule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTaxCalculationRule() {
    return taxCalculationRule;
  }


  public void setTaxCalculationRule(String taxCalculationRule) {
    
    
    
    this.taxCalculationRule = taxCalculationRule;
  }


  public EarningsDto exemptFromEarnedIncomeHours(String exemptFromEarnedIncomeHours) {
    
    
    
    
    this.exemptFromEarnedIncomeHours = exemptFromEarnedIncomeHours;
    return this;
  }

   /**
   * Get exemptFromEarnedIncomeHours
   * @return exemptFromEarnedIncomeHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExemptFromEarnedIncomeHours() {
    return exemptFromEarnedIncomeHours;
  }


  public void setExemptFromEarnedIncomeHours(String exemptFromEarnedIncomeHours) {
    
    
    
    this.exemptFromEarnedIncomeHours = exemptFromEarnedIncomeHours;
  }


  public EarningsDto includeInHealthCareHours(Boolean includeInHealthCareHours) {
    
    
    
    
    this.includeInHealthCareHours = includeInHealthCareHours;
    return this;
  }

   /**
   * Get includeInHealthCareHours
   * @return includeInHealthCareHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncludeInHealthCareHours() {
    return includeInHealthCareHours;
  }


  public void setIncludeInHealthCareHours(Boolean includeInHealthCareHours) {
    
    
    
    this.includeInHealthCareHours = includeInHealthCareHours;
  }


  public EarningsDto verificationTypeCode(String verificationTypeCode) {
    
    
    
    
    this.verificationTypeCode = verificationTypeCode;
    return this;
  }

   /**
   * Get verificationTypeCode
   * @return verificationTypeCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVerificationTypeCode() {
    return verificationTypeCode;
  }


  public void setVerificationTypeCode(String verificationTypeCode) {
    
    
    
    this.verificationTypeCode = verificationTypeCode;
  }


  public EarningsDto verificationTypeDescription(String verificationTypeDescription) {
    
    
    
    
    this.verificationTypeDescription = verificationTypeDescription;
    return this;
  }

   /**
   * Get verificationTypeDescription
   * @return verificationTypeDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVerificationTypeDescription() {
    return verificationTypeDescription;
  }


  public void setVerificationTypeDescription(String verificationTypeDescription) {
    
    
    
    this.verificationTypeDescription = verificationTypeDescription;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EarningsDto instance itself
   */
  public EarningsDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningsDto earningsDto = (EarningsDto) o;
    return Objects.equals(this.earningCode, earningsDto.earningCode) &&
        Objects.equals(this.longDescription, earningsDto.longDescription) &&
        Objects.equals(this.amount, earningsDto.amount) &&
        Objects.equals(this.blockFederalIncomeTax, earningsDto.blockFederalIncomeTax) &&
        Objects.equals(this.blockLocalIncomeTax, earningsDto.blockLocalIncomeTax) &&
        Objects.equals(this.blockStateIncomeTax, earningsDto.blockStateIncomeTax) &&
        Objects.equals(this.calculationRule, earningsDto.calculationRule) &&
        Objects.equals(this.displayInPayDataEntry, earningsDto.displayInPayDataEntry) &&
        Objects.equals(this.excelInTotalHours, earningsDto.excelInTotalHours) &&
        Objects.equals(this.flatHours, earningsDto.flatHours) &&
        Objects.equals(this.includeInAccruals, earningsDto.includeInAccruals) &&
        Objects.equals(this.includeInAllocations, earningsDto.includeInAllocations) &&
        Objects.equals(this.includeFlsaAveragePayRate, earningsDto.includeFlsaAveragePayRate) &&
        Objects.equals(this.includeInBenefitHours, earningsDto.includeInBenefitHours) &&
        Objects.equals(this.includeInDeferredCompensation, earningsDto.includeInDeferredCompensation) &&
        Objects.equals(this.includeInDeferredCompensationHours, earningsDto.includeInDeferredCompensationHours) &&
        Objects.equals(this.includeInEarningAccumulation, earningsDto.includeInEarningAccumulation) &&
        Objects.equals(this.includeInHoursAccumulation, earningsDto.includeInHoursAccumulation) &&
        Objects.equals(this.includeInManualCheck, earningsDto.includeInManualCheck) &&
        Objects.equals(this.includeInMiscellaneousEarning1, earningsDto.includeInMiscellaneousEarning1) &&
        Objects.equals(this.includeInMiscellaneousEarning2, earningsDto.includeInMiscellaneousEarning2) &&
        Objects.equals(this.includeInMiscellaneousEarning3, earningsDto.includeInMiscellaneousEarning3) &&
        Objects.equals(this.includeInMiscellaneousEarning4, earningsDto.includeInMiscellaneousEarning4) &&
        Objects.equals(this.includeInMiscellaneousEarning5, earningsDto.includeInMiscellaneousEarning5) &&
        Objects.equals(this.includeInMiscellaneousEarning6, earningsDto.includeInMiscellaneousEarning6) &&
        Objects.equals(this.includeInPensionAccumulation, earningsDto.includeInPensionAccumulation) &&
        Objects.equals(this.includeInRetroPay, earningsDto.includeInRetroPay) &&
        Objects.equals(this.includeInShiftDiffrential, earningsDto.includeInShiftDiffrential) &&
        Objects.equals(this.isProductiveTime, earningsDto.isProductiveTime) &&
        Objects.equals(this.isSupplimentalWages, earningsDto.isSupplimentalWages) &&
        Objects.equals(this.monthlyPayPeriod1, earningsDto.monthlyPayPeriod1) &&
        Objects.equals(this.monthlyPayPeriod2, earningsDto.monthlyPayPeriod2) &&
        Objects.equals(this.monthlyPayPeriod3, earningsDto.monthlyPayPeriod3) &&
        Objects.equals(this.monthlyPayPeriod4, earningsDto.monthlyPayPeriod4) &&
        Objects.equals(this.monthlyPayPeriod5, earningsDto.monthlyPayPeriod5) &&
        Objects.equals(this.notes, earningsDto.notes) &&
        Objects.equals(this.reduceRegularDollars, earningsDto.reduceRegularDollars) &&
        Objects.equals(this.reduceRegularHours, earningsDto.reduceRegularHours) &&
        Objects.equals(this.reportCategory, earningsDto.reportCategory) &&
        Objects.equals(this.scheduleSupplemental, earningsDto.scheduleSupplemental) &&
        Objects.equals(this.stubDescription, earningsDto.stubDescription) &&
        Objects.equals(this.taxCategory, earningsDto.taxCategory) &&
        Objects.equals(this.timeClockCode, earningsDto.timeClockCode) &&
        Objects.equals(this.countryCode, earningsDto.countryCode) &&
        Objects.equals(this.useDeductionOffset, earningsDto.useDeductionOffset) &&
        Objects.equals(this.includeInRegisteredPensionPlan, earningsDto.includeInRegisteredPensionPlan) &&
        Objects.equals(this.includeInRegisteredRetirementSavingsPlan, earningsDto.includeInRegisteredRetirementSavingsPlan) &&
        Objects.equals(this.includeInUnionDues, earningsDto.includeInUnionDues) &&
        Objects.equals(this.includeInUnionDuesHours, earningsDto.includeInUnionDuesHours) &&
        Objects.equals(this.taxCalculationRule, earningsDto.taxCalculationRule) &&
        Objects.equals(this.exemptFromEarnedIncomeHours, earningsDto.exemptFromEarnedIncomeHours) &&
        Objects.equals(this.includeInHealthCareHours, earningsDto.includeInHealthCareHours) &&
        Objects.equals(this.verificationTypeCode, earningsDto.verificationTypeCode) &&
        Objects.equals(this.verificationTypeDescription, earningsDto.verificationTypeDescription)&&
        Objects.equals(this.additionalProperties, earningsDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earningCode, longDescription, amount, blockFederalIncomeTax, blockLocalIncomeTax, blockStateIncomeTax, calculationRule, displayInPayDataEntry, excelInTotalHours, flatHours, includeInAccruals, includeInAllocations, includeFlsaAveragePayRate, includeInBenefitHours, includeInDeferredCompensation, includeInDeferredCompensationHours, includeInEarningAccumulation, includeInHoursAccumulation, includeInManualCheck, includeInMiscellaneousEarning1, includeInMiscellaneousEarning2, includeInMiscellaneousEarning3, includeInMiscellaneousEarning4, includeInMiscellaneousEarning5, includeInMiscellaneousEarning6, includeInPensionAccumulation, includeInRetroPay, includeInShiftDiffrential, isProductiveTime, isSupplimentalWages, monthlyPayPeriod1, monthlyPayPeriod2, monthlyPayPeriod3, monthlyPayPeriod4, monthlyPayPeriod5, notes, reduceRegularDollars, reduceRegularHours, reportCategory, scheduleSupplemental, stubDescription, taxCategory, timeClockCode, countryCode, useDeductionOffset, includeInRegisteredPensionPlan, includeInRegisteredRetirementSavingsPlan, includeInUnionDues, includeInUnionDuesHours, taxCalculationRule, exemptFromEarnedIncomeHours, includeInHealthCareHours, verificationTypeCode, verificationTypeDescription, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningsDto {\n");
    sb.append("    earningCode: ").append(toIndentedString(earningCode)).append("\n");
    sb.append("    longDescription: ").append(toIndentedString(longDescription)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    blockFederalIncomeTax: ").append(toIndentedString(blockFederalIncomeTax)).append("\n");
    sb.append("    blockLocalIncomeTax: ").append(toIndentedString(blockLocalIncomeTax)).append("\n");
    sb.append("    blockStateIncomeTax: ").append(toIndentedString(blockStateIncomeTax)).append("\n");
    sb.append("    calculationRule: ").append(toIndentedString(calculationRule)).append("\n");
    sb.append("    displayInPayDataEntry: ").append(toIndentedString(displayInPayDataEntry)).append("\n");
    sb.append("    excelInTotalHours: ").append(toIndentedString(excelInTotalHours)).append("\n");
    sb.append("    flatHours: ").append(toIndentedString(flatHours)).append("\n");
    sb.append("    includeInAccruals: ").append(toIndentedString(includeInAccruals)).append("\n");
    sb.append("    includeInAllocations: ").append(toIndentedString(includeInAllocations)).append("\n");
    sb.append("    includeFlsaAveragePayRate: ").append(toIndentedString(includeFlsaAveragePayRate)).append("\n");
    sb.append("    includeInBenefitHours: ").append(toIndentedString(includeInBenefitHours)).append("\n");
    sb.append("    includeInDeferredCompensation: ").append(toIndentedString(includeInDeferredCompensation)).append("\n");
    sb.append("    includeInDeferredCompensationHours: ").append(toIndentedString(includeInDeferredCompensationHours)).append("\n");
    sb.append("    includeInEarningAccumulation: ").append(toIndentedString(includeInEarningAccumulation)).append("\n");
    sb.append("    includeInHoursAccumulation: ").append(toIndentedString(includeInHoursAccumulation)).append("\n");
    sb.append("    includeInManualCheck: ").append(toIndentedString(includeInManualCheck)).append("\n");
    sb.append("    includeInMiscellaneousEarning1: ").append(toIndentedString(includeInMiscellaneousEarning1)).append("\n");
    sb.append("    includeInMiscellaneousEarning2: ").append(toIndentedString(includeInMiscellaneousEarning2)).append("\n");
    sb.append("    includeInMiscellaneousEarning3: ").append(toIndentedString(includeInMiscellaneousEarning3)).append("\n");
    sb.append("    includeInMiscellaneousEarning4: ").append(toIndentedString(includeInMiscellaneousEarning4)).append("\n");
    sb.append("    includeInMiscellaneousEarning5: ").append(toIndentedString(includeInMiscellaneousEarning5)).append("\n");
    sb.append("    includeInMiscellaneousEarning6: ").append(toIndentedString(includeInMiscellaneousEarning6)).append("\n");
    sb.append("    includeInPensionAccumulation: ").append(toIndentedString(includeInPensionAccumulation)).append("\n");
    sb.append("    includeInRetroPay: ").append(toIndentedString(includeInRetroPay)).append("\n");
    sb.append("    includeInShiftDiffrential: ").append(toIndentedString(includeInShiftDiffrential)).append("\n");
    sb.append("    isProductiveTime: ").append(toIndentedString(isProductiveTime)).append("\n");
    sb.append("    isSupplimentalWages: ").append(toIndentedString(isSupplimentalWages)).append("\n");
    sb.append("    monthlyPayPeriod1: ").append(toIndentedString(monthlyPayPeriod1)).append("\n");
    sb.append("    monthlyPayPeriod2: ").append(toIndentedString(monthlyPayPeriod2)).append("\n");
    sb.append("    monthlyPayPeriod3: ").append(toIndentedString(monthlyPayPeriod3)).append("\n");
    sb.append("    monthlyPayPeriod4: ").append(toIndentedString(monthlyPayPeriod4)).append("\n");
    sb.append("    monthlyPayPeriod5: ").append(toIndentedString(monthlyPayPeriod5)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    reduceRegularDollars: ").append(toIndentedString(reduceRegularDollars)).append("\n");
    sb.append("    reduceRegularHours: ").append(toIndentedString(reduceRegularHours)).append("\n");
    sb.append("    reportCategory: ").append(toIndentedString(reportCategory)).append("\n");
    sb.append("    scheduleSupplemental: ").append(toIndentedString(scheduleSupplemental)).append("\n");
    sb.append("    stubDescription: ").append(toIndentedString(stubDescription)).append("\n");
    sb.append("    taxCategory: ").append(toIndentedString(taxCategory)).append("\n");
    sb.append("    timeClockCode: ").append(toIndentedString(timeClockCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    useDeductionOffset: ").append(toIndentedString(useDeductionOffset)).append("\n");
    sb.append("    includeInRegisteredPensionPlan: ").append(toIndentedString(includeInRegisteredPensionPlan)).append("\n");
    sb.append("    includeInRegisteredRetirementSavingsPlan: ").append(toIndentedString(includeInRegisteredRetirementSavingsPlan)).append("\n");
    sb.append("    includeInUnionDues: ").append(toIndentedString(includeInUnionDues)).append("\n");
    sb.append("    includeInUnionDuesHours: ").append(toIndentedString(includeInUnionDuesHours)).append("\n");
    sb.append("    taxCalculationRule: ").append(toIndentedString(taxCalculationRule)).append("\n");
    sb.append("    exemptFromEarnedIncomeHours: ").append(toIndentedString(exemptFromEarnedIncomeHours)).append("\n");
    sb.append("    includeInHealthCareHours: ").append(toIndentedString(includeInHealthCareHours)).append("\n");
    sb.append("    verificationTypeCode: ").append(toIndentedString(verificationTypeCode)).append("\n");
    sb.append("    verificationTypeDescription: ").append(toIndentedString(verificationTypeDescription)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("earningCode");
    openapiFields.add("longDescription");
    openapiFields.add("amount");
    openapiFields.add("blockFederalIncomeTax");
    openapiFields.add("blockLocalIncomeTax");
    openapiFields.add("blockStateIncomeTax");
    openapiFields.add("calculationRule");
    openapiFields.add("displayInPayDataEntry");
    openapiFields.add("excelInTotalHours");
    openapiFields.add("flatHours");
    openapiFields.add("includeInAccruals");
    openapiFields.add("includeInAllocations");
    openapiFields.add("includeFlsaAveragePayRate");
    openapiFields.add("includeInBenefitHours");
    openapiFields.add("includeInDeferredCompensation");
    openapiFields.add("includeInDeferredCompensationHours");
    openapiFields.add("includeInEarningAccumulation");
    openapiFields.add("includeInHoursAccumulation");
    openapiFields.add("includeInManualCheck");
    openapiFields.add("includeInMiscellaneousEarning1");
    openapiFields.add("includeInMiscellaneousEarning2");
    openapiFields.add("includeInMiscellaneousEarning3");
    openapiFields.add("includeInMiscellaneousEarning4");
    openapiFields.add("includeInMiscellaneousEarning5");
    openapiFields.add("includeInMiscellaneousEarning6");
    openapiFields.add("includeInPensionAccumulation");
    openapiFields.add("includeInRetroPay");
    openapiFields.add("includeInShiftDiffrential");
    openapiFields.add("isProductiveTime");
    openapiFields.add("isSupplimentalWages");
    openapiFields.add("monthlyPayPeriod1");
    openapiFields.add("monthlyPayPeriod2");
    openapiFields.add("monthlyPayPeriod3");
    openapiFields.add("monthlyPayPeriod4");
    openapiFields.add("monthlyPayPeriod5");
    openapiFields.add("notes");
    openapiFields.add("reduceRegularDollars");
    openapiFields.add("reduceRegularHours");
    openapiFields.add("reportCategory");
    openapiFields.add("scheduleSupplemental");
    openapiFields.add("stubDescription");
    openapiFields.add("taxCategory");
    openapiFields.add("timeClockCode");
    openapiFields.add("countryCode");
    openapiFields.add("useDeductionOffset");
    openapiFields.add("includeInRegisteredPensionPlan");
    openapiFields.add("includeInRegisteredRetirementSavingsPlan");
    openapiFields.add("includeInUnionDues");
    openapiFields.add("includeInUnionDuesHours");
    openapiFields.add("taxCalculationRule");
    openapiFields.add("exemptFromEarnedIncomeHours");
    openapiFields.add("includeInHealthCareHours");
    openapiFields.add("verificationTypeCode");
    openapiFields.add("verificationTypeDescription");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("earningCode");
    openapiRequiredFields.add("longDescription");
    openapiRequiredFields.add("stubDescription");
    openapiRequiredFields.add("timeClockCode");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EarningsDto
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EarningsDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EarningsDto is not found in the empty JSON string", EarningsDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EarningsDto.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("earningCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `earningCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("earningCode").toString()));
      }
      if (!jsonObj.get("longDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `longDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("longDescription").toString()));
      }
      if ((jsonObj.get("calculationRule") != null && !jsonObj.get("calculationRule").isJsonNull()) && !jsonObj.get("calculationRule").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `calculationRule` to be a primitive type in the JSON string but got `%s`", jsonObj.get("calculationRule").toString()));
      }
      if ((jsonObj.get("includeInAccruals") != null && !jsonObj.get("includeInAccruals").isJsonNull()) && !jsonObj.get("includeInAccruals").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `includeInAccruals` to be a primitive type in the JSON string but got `%s`", jsonObj.get("includeInAccruals").toString()));
      }
      if ((jsonObj.get("notes") != null && !jsonObj.get("notes").isJsonNull()) && !jsonObj.get("notes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notes").toString()));
      }
      if ((jsonObj.get("reportCategory") != null && !jsonObj.get("reportCategory").isJsonNull()) && !jsonObj.get("reportCategory").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reportCategory` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reportCategory").toString()));
      }
      if (!jsonObj.get("stubDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stubDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stubDescription").toString()));
      }
      if ((jsonObj.get("taxCategory") != null && !jsonObj.get("taxCategory").isJsonNull()) && !jsonObj.get("taxCategory").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxCategory` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taxCategory").toString()));
      }
      if (!jsonObj.get("timeClockCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeClockCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeClockCode").toString()));
      }
      if ((jsonObj.get("countryCode") != null && !jsonObj.get("countryCode").isJsonNull()) && !jsonObj.get("countryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCode").toString()));
      }
      if ((jsonObj.get("taxCalculationRule") != null && !jsonObj.get("taxCalculationRule").isJsonNull()) && !jsonObj.get("taxCalculationRule").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxCalculationRule` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taxCalculationRule").toString()));
      }
      if ((jsonObj.get("exemptFromEarnedIncomeHours") != null && !jsonObj.get("exemptFromEarnedIncomeHours").isJsonNull()) && !jsonObj.get("exemptFromEarnedIncomeHours").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `exemptFromEarnedIncomeHours` to be a primitive type in the JSON string but got `%s`", jsonObj.get("exemptFromEarnedIncomeHours").toString()));
      }
      if ((jsonObj.get("verificationTypeCode") != null && !jsonObj.get("verificationTypeCode").isJsonNull()) && !jsonObj.get("verificationTypeCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `verificationTypeCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verificationTypeCode").toString()));
      }
      if ((jsonObj.get("verificationTypeDescription") != null && !jsonObj.get("verificationTypeDescription").isJsonNull()) && !jsonObj.get("verificationTypeDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `verificationTypeDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verificationTypeDescription").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EarningsDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EarningsDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EarningsDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EarningsDto.class));

       return (TypeAdapter<T>) new TypeAdapter<EarningsDto>() {
           @Override
           public void write(JsonWriter out, EarningsDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EarningsDto read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EarningsDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EarningsDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EarningsDto
  * @throws IOException if the JSON string is invalid with respect to EarningsDto
  */
  public static EarningsDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EarningsDto.class);
  }

 /**
  * Convert an instance of EarningsDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

