/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * EmployeeJobDto
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EmployeeJobDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_JOB_NAME = "jobName";
  @SerializedName(SERIALIZED_NAME_JOB_NAME)
  private String jobName;

  public static final String SERIALIZED_NAME_JOB_DESC = "jobDesc";
  @SerializedName(SERIALIZED_NAME_JOB_DESC)
  private String jobDesc;

  public static final String SERIALIZED_NAME_JOB_START_DATE = "jobStartDate";
  @SerializedName(SERIALIZED_NAME_JOB_START_DATE)
  private OffsetDateTime jobStartDate;

  public static final String SERIALIZED_NAME_JOB_END_DATE = "jobEndDate";
  @SerializedName(SERIALIZED_NAME_JOB_END_DATE)
  private OffsetDateTime jobEndDate;

  public static final String SERIALIZED_NAME_JOB_PREFERRED = "jobPreferred";
  @SerializedName(SERIALIZED_NAME_JOB_PREFERRED)
  private Boolean jobPreferred = false;

  public EmployeeJobDto() {
  }

  public EmployeeJobDto id(Long id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    
    
    
    this.id = id;
  }


  public EmployeeJobDto jobName(String jobName) {
    
    
    
    
    this.jobName = jobName;
    return this;
  }

   /**
   * Get jobName
   * @return jobName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getJobName() {
    return jobName;
  }


  public void setJobName(String jobName) {
    
    
    
    this.jobName = jobName;
  }


  public EmployeeJobDto jobDesc(String jobDesc) {
    
    
    
    
    this.jobDesc = jobDesc;
    return this;
  }

   /**
   * Get jobDesc
   * @return jobDesc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getJobDesc() {
    return jobDesc;
  }


  public void setJobDesc(String jobDesc) {
    
    
    
    this.jobDesc = jobDesc;
  }


  public EmployeeJobDto jobStartDate(OffsetDateTime jobStartDate) {
    
    
    
    
    this.jobStartDate = jobStartDate;
    return this;
  }

   /**
   * Get jobStartDate
   * @return jobStartDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getJobStartDate() {
    return jobStartDate;
  }


  public void setJobStartDate(OffsetDateTime jobStartDate) {
    
    
    
    this.jobStartDate = jobStartDate;
  }


  public EmployeeJobDto jobEndDate(OffsetDateTime jobEndDate) {
    
    
    
    
    this.jobEndDate = jobEndDate;
    return this;
  }

   /**
   * Get jobEndDate
   * @return jobEndDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getJobEndDate() {
    return jobEndDate;
  }


  public void setJobEndDate(OffsetDateTime jobEndDate) {
    
    
    
    this.jobEndDate = jobEndDate;
  }


  public EmployeeJobDto jobPreferred(Boolean jobPreferred) {
    
    
    
    
    this.jobPreferred = jobPreferred;
    return this;
  }

   /**
   * Get jobPreferred
   * @return jobPreferred
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getJobPreferred() {
    return jobPreferred;
  }


  public void setJobPreferred(Boolean jobPreferred) {
    
    
    
    this.jobPreferred = jobPreferred;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EmployeeJobDto instance itself
   */
  public EmployeeJobDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeJobDto employeeJobDto = (EmployeeJobDto) o;
    return Objects.equals(this.id, employeeJobDto.id) &&
        Objects.equals(this.jobName, employeeJobDto.jobName) &&
        Objects.equals(this.jobDesc, employeeJobDto.jobDesc) &&
        Objects.equals(this.jobStartDate, employeeJobDto.jobStartDate) &&
        Objects.equals(this.jobEndDate, employeeJobDto.jobEndDate) &&
        Objects.equals(this.jobPreferred, employeeJobDto.jobPreferred)&&
        Objects.equals(this.additionalProperties, employeeJobDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, jobName, jobDesc, jobStartDate, jobEndDate, jobPreferred, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeJobDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    jobDesc: ").append(toIndentedString(jobDesc)).append("\n");
    sb.append("    jobStartDate: ").append(toIndentedString(jobStartDate)).append("\n");
    sb.append("    jobEndDate: ").append(toIndentedString(jobEndDate)).append("\n");
    sb.append("    jobPreferred: ").append(toIndentedString(jobPreferred)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("jobName");
    openapiFields.add("jobDesc");
    openapiFields.add("jobStartDate");
    openapiFields.add("jobEndDate");
    openapiFields.add("jobPreferred");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EmployeeJobDto
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EmployeeJobDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmployeeJobDto is not found in the empty JSON string", EmployeeJobDto.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("jobName") != null && !jsonObj.get("jobName").isJsonNull()) && !jsonObj.get("jobName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jobName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jobName").toString()));
      }
      if ((jsonObj.get("jobDesc") != null && !jsonObj.get("jobDesc").isJsonNull()) && !jsonObj.get("jobDesc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jobDesc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jobDesc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmployeeJobDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmployeeJobDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmployeeJobDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmployeeJobDto.class));

       return (TypeAdapter<T>) new TypeAdapter<EmployeeJobDto>() {
           @Override
           public void write(JsonWriter out, EmployeeJobDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EmployeeJobDto read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EmployeeJobDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EmployeeJobDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EmployeeJobDto
  * @throws IOException if the JSON string is invalid with respect to EmployeeJobDto
  */
  public static EmployeeJobDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmployeeJobDto.class);
  }

 /**
  * Convert an instance of EmployeeJobDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

