/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TimeItem
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TimeItem {
  public static final String SERIALIZED_NAME_EMPLOYEE_NUMBER = "employeeNumber";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_NUMBER)
  private String employeeNumber;

  public static final String SERIALIZED_NAME_EE_ID = "eeId";
  @SerializedName(SERIALIZED_NAME_EE_ID)
  private String eeId;

  public static final String SERIALIZED_NAME_COMPANY_CODE = "companyCode";
  @SerializedName(SERIALIZED_NAME_COMPANY_CODE)
  private String companyCode;

  public static final String SERIALIZED_NAME_CO_ID = "coId";
  @SerializedName(SERIALIZED_NAME_CO_ID)
  private String coId;

  public static final String SERIALIZED_NAME_DATE_WORKED = "dateWorked";
  @SerializedName(SERIALIZED_NAME_DATE_WORKED)
  private OffsetDateTime dateWorked;

  public static final String SERIALIZED_NAME_HOURS_WORKED = "hoursWorked";
  @SerializedName(SERIALIZED_NAME_HOURS_WORKED)
  private Double hoursWorked;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Double id;

  public TimeItem() {
  }

  public TimeItem employeeNumber(String employeeNumber) {
    
    
    
    
    this.employeeNumber = employeeNumber;
    return this;
  }

   /**
   * The UltiPro EmployeeNumber, either this value OR the EEID MUST be specified
   * @return employeeNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UltiPro EmployeeNumber, either this value OR the EEID MUST be specified")

  public String getEmployeeNumber() {
    return employeeNumber;
  }


  public void setEmployeeNumber(String employeeNumber) {
    
    
    
    this.employeeNumber = employeeNumber;
  }


  public TimeItem eeId(String eeId) {
    
    
    if (eeId != null && eeId.length() < 12) {
      throw new IllegalArgumentException("Invalid value for eeId. Length must be greater than or equal to 12.");
    }
    
    this.eeId = eeId;
    return this;
  }

   /**
   * The UltiPro EEID, either this value OR the EmployeeNumber MUST be specified
   * @return eeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UltiPro EEID, either this value OR the EmployeeNumber MUST be specified")

  public String getEeId() {
    return eeId;
  }


  public void setEeId(String eeId) {
    
    
    if (eeId != null && eeId.length() < 12) {
      throw new IllegalArgumentException("Invalid value for eeId. Length must be greater than or equal to 12.");
    }
    this.eeId = eeId;
  }


  public TimeItem companyCode(String companyCode) {
    
    
    
    
    this.companyCode = companyCode;
    return this;
  }

   /**
   * The UltiPro CompanyCode, either this value OR the CoID MUST be specified
   * @return companyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UltiPro CompanyCode, either this value OR the CoID MUST be specified")

  public String getCompanyCode() {
    return companyCode;
  }


  public void setCompanyCode(String companyCode) {
    
    
    
    this.companyCode = companyCode;
  }


  public TimeItem coId(String coId) {
    
    
    if (coId != null && coId.length() < 5) {
      throw new IllegalArgumentException("Invalid value for coId. Length must be greater than or equal to 5.");
    }
    
    this.coId = coId;
    return this;
  }

   /**
   * The UltiPro CoID, either this value OR the CompanyCode MUST be specified
   * @return coId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UltiPro CoID, either this value OR the CompanyCode MUST be specified")

  public String getCoId() {
    return coId;
  }


  public void setCoId(String coId) {
    
    
    if (coId != null && coId.length() < 5) {
      throw new IllegalArgumentException("Invalid value for coId. Length must be greater than or equal to 5.");
    }
    this.coId = coId;
  }


  public TimeItem dateWorked(OffsetDateTime dateWorked) {
    
    
    
    
    this.dateWorked = dateWorked;
    return this;
  }

   /**
   * The date the hours were worked
   * @return dateWorked
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The date the hours were worked")

  public OffsetDateTime getDateWorked() {
    return dateWorked;
  }


  public void setDateWorked(OffsetDateTime dateWorked) {
    
    
    
    this.dateWorked = dateWorked;
  }


  public TimeItem hoursWorked(Double hoursWorked) {
    
    
    
    
    this.hoursWorked = hoursWorked;
    return this;
  }

  public TimeItem hoursWorked(Integer hoursWorked) {
    
    
    
    
    this.hoursWorked = hoursWorked.doubleValue();
    return this;
  }

   /**
   * The number of hours worked
   * @return hoursWorked
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of hours worked")

  public Double getHoursWorked() {
    return hoursWorked;
  }


  public void setHoursWorked(Double hoursWorked) {
    
    
    
    this.hoursWorked = hoursWorked;
  }


  public TimeItem id(Double id) {
    
    
    
    
    this.id = id;
    return this;
  }

  public TimeItem id(Integer id) {
    
    
    
    
    this.id = id.doubleValue();
    return this;
  }

   /**
   * This value should be NULL from the originator
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This value should be NULL from the originator")

  public Double getId() {
    return id;
  }


  public void setId(Double id) {
    
    
    
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TimeItem instance itself
   */
  public TimeItem putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeItem timeItem = (TimeItem) o;
    return Objects.equals(this.employeeNumber, timeItem.employeeNumber) &&
        Objects.equals(this.eeId, timeItem.eeId) &&
        Objects.equals(this.companyCode, timeItem.companyCode) &&
        Objects.equals(this.coId, timeItem.coId) &&
        Objects.equals(this.dateWorked, timeItem.dateWorked) &&
        Objects.equals(this.hoursWorked, timeItem.hoursWorked) &&
        Objects.equals(this.id, timeItem.id)&&
        Objects.equals(this.additionalProperties, timeItem.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeNumber, eeId, companyCode, coId, dateWorked, hoursWorked, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeItem {\n");
    sb.append("    employeeNumber: ").append(toIndentedString(employeeNumber)).append("\n");
    sb.append("    eeId: ").append(toIndentedString(eeId)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    coId: ").append(toIndentedString(coId)).append("\n");
    sb.append("    dateWorked: ").append(toIndentedString(dateWorked)).append("\n");
    sb.append("    hoursWorked: ").append(toIndentedString(hoursWorked)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("employeeNumber");
    openapiFields.add("eeId");
    openapiFields.add("companyCode");
    openapiFields.add("coId");
    openapiFields.add("dateWorked");
    openapiFields.add("hoursWorked");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("dateWorked");
    openapiRequiredFields.add("hoursWorked");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TimeItem
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TimeItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TimeItem is not found in the empty JSON string", TimeItem.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TimeItem.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("employeeNumber") != null && !jsonObj.get("employeeNumber").isJsonNull()) && !jsonObj.get("employeeNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeNumber").toString()));
      }
      if ((jsonObj.get("eeId") != null && !jsonObj.get("eeId").isJsonNull()) && !jsonObj.get("eeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eeId").toString()));
      }
      if ((jsonObj.get("companyCode") != null && !jsonObj.get("companyCode").isJsonNull()) && !jsonObj.get("companyCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyCode").toString()));
      }
      if ((jsonObj.get("coId") != null && !jsonObj.get("coId").isJsonNull()) && !jsonObj.get("coId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `coId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("coId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TimeItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TimeItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TimeItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TimeItem.class));

       return (TypeAdapter<T>) new TypeAdapter<TimeItem>() {
           @Override
           public void write(JsonWriter out, TimeItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TimeItem read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TimeItem instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TimeItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TimeItem
  * @throws IOException if the JSON string is invalid with respect to TimeItem
  */
  public static TimeItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TimeItem.class);
  }

 /**
  * Convert an instance of TimeItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

