/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CompanyPayStatementFilter;
import com.konfigthis.client.model.CompanyPayStatementModel;
import com.konfigthis.client.model.EmployeePayStatementModel;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyPayStatementApi
 */
@Disabled
public class CompanyPayStatementApiTest {

    private static CompanyPayStatementApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CompanyPayStatementApi(apiClient);
    }

    /**
     * Get employee(s) pay statement(s) for a company or pay group for a given date range.
     *
     * This method returns zero or more full pay statement documents for a given start date and end date. You may also pass in a PayGroup or CompanyIdentifer to further filter the list of pay summaries returned. &lt;br /&gt;If no pagination parameters specified, the default is applied. Permissions - UKG Pro service account must have \&quot;View\&quot; role for the \&quot;Employee Pay Statements\&quot; Web Service. Headers - US-Customer-Api-Key, US-Client-id, Authorization ({username}:{password}).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByDateRangeTest() throws ApiException {
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        String companyId = null;
        String payGroup = null;
        Integer page = null;
        Integer perPage = null;
        Integer pagesCount = null;
        List<EmployeePayStatementModel> response = api.getByDateRange(startDate, endDate)
                .companyId(companyId)
                .payGroup(payGroup)
                .page(page)
                .perPage(perPage)
                .pagesCount(pagesCount)
                .execute();
        // TODO: test validations
    }

    /**
     * Get employee(s) pay statement(s) summary for a company or pay group for a given date range.
     *
     * This method returns zero or more pay statement summaries for a given start date and end date. The pay summary information gives you a quick view of the total earnings, deductions and taxes. You may also pass in a PayGroup or CompanyIdentifer to further filter the list of pay summaries returned. &lt;br /&gt;If no pagination parameters specified, the default is applied. Permissions - UKG Pro service account must have \&quot;View\&quot; role for the \&quot;Employee Pay Statements\&quot; Web Service. Headers - US-Customer-Api-Key, US-Client-id, Authorization ({username}:{password}).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaySummariesTest() throws ApiException {
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        String companyId = null;
        String payGroup = null;
        Integer page = null;
        Integer perPage = null;
        Integer pagesCount = null;
        List<CompanyPayStatementModel> response = api.getPaySummaries(startDate, endDate)
                .companyId(companyId)
                .payGroup(payGroup)
                .page(page)
                .perPage(perPage)
                .pagesCount(pagesCount)
                .execute();
        // TODO: test validations
    }

}
