/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.time.OffsetDateTime;
import com.konfigthis.client.model.OptionRate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OptionRateApi
 */
@Disabled
public class OptionRateApiTest {

    private static OptionRateApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OptionRateApi(apiClient);
    }

    /**
     * Get Option Rate Data
     *
     * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \\\&quot;View\\\&quot; role for the \\\&quot;Company Configuration Integration\\\&quot; Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).  Effective date parameter gets effective record as of the given date. If it&#39;s not passed, effected date is defaulted to current date.  Deduction code parameter can take in multiple deduction codes separated by coma. ex: [DEN, MED, VIS] .  Pay frequency parameter can take in multiple pay frequencies separated by coma. ex: [B, M] . 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataTest() throws ApiException {
        String deductionCode = null;
        String benefitOption = null;
        OffsetDateTime effectiveDate = null;
        String payFrequency = null;
        Integer page = null;
        Integer perPage = null;
        List<OptionRate> response = api.getData()
                .deductionCode(deductionCode)
                .benefitOption(benefitOption)
                .effectiveDate(effectiveDate)
                .payFrequency(payFrequency)
                .page(page)
                .perPage(perPage)
                .execute();
        // TODO: test validations
    }

}
