/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Output;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderRequestsApi
 */
@Disabled
public class OrderRequestsApiTest {

    private static OrderRequestsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OrderRequestsApi(apiClient);
    }

    /**
     * Background Check Details
     *
     * Background Check Order Request with Candidate, Application, and Opportunity info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void backgroundCheckDetailsTest() throws ApiException {
        String token = null;
        String tenantAlias = null;
        Output response = api.backgroundCheckDetails(token, tenantAlias)
                .execute();
        // TODO: test validations
    }

}
