/*
 * User Profile Details
 * Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.MultiStatusResponse;
import com.konfigthis.client.model.OrgLevels;
import com.konfigthis.client.model.OrgLevelsBodyInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ViewOrCreateOrganizationLevelsApi
 */
@Disabled
public class ViewOrCreateOrganizationLevelsApiTest {

    private static ViewOrCreateOrganizationLevelsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ViewOrCreateOrganizationLevelsApi(apiClient);
    }

    /**
     * Create org-level configuration
     *
     * Creates a new UltiPro org-level configuration, Array of objects is permitted for multi-records support. Permissions - Ultipro service account must have \&quot;Add\&quot; role for the \&quot;Company Configuration Integration\&quot; Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrgLevelConfigTest() throws ApiException {
        MultiStatusResponse response = api.createOrgLevelConfig()
                .execute();
        // TODO: test validations
    }

    /**
     * Get all org-levels
     *
     * Returns information about the UltiPro org-level configurations. Permissions - Ultipro service account must have \&quot;View\&quot; role for the \&quot;Company Configuration Integration\&quot; Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllOrgLevelsTest() throws ApiException {
        String levelDescription = null;
        String code = null;
        String budgetGroup = null;
        String reportingCategory = null;
        Boolean isActive = null;
        List<OrgLevels> response = api.getAllOrgLevels()
                .levelDescription(levelDescription)
                .code(code)
                .budgetGroup(budgetGroup)
                .reportingCategory(reportingCategory)
                .isActive(isActive)
                .execute();
        // TODO: test validations
    }

}
